[team-03 FE] Week1 PR
codesquad-members-2023/issue-tracker pull request #10
Opened 2023-05-12 02:23 UTC by sjuhan123

안녕하세요 빰빰,

한 주가 금방 지나갔네요.
이번 주는 처음 접하는 상황도 많고, 그룹 프로젝트가 처음이라 아직 구현한 코드가 거의 없습니다.
그래서 진행상황 공유 드리고, 저와 시저 각각 구현한 내용, 그리고 고민했던 내용 중심 공유 드립니다. 

# 📍 구현 진행 된 내용

### 현 시점 담당 구역
![image](https://user-images.githubusercontent.com/81420856/237850956-73f0ebb9-4b26-4713-9765-8118230ad55e.png)

### 진행된 내용
![image](https://user-images.githubusercontent.com/81420856/237851661-7a0b6f94-831f-4ad9-9fe0-e8e966ac14c6.png)

# 📍공통

## 구현

초기 뷰 정도만 구현 진행했습니다.

## Styled-components로 바꾼 이유

저희가 예상했던 것 보다 러닝 커브가 생각보다 높지 않아서, css-module을 사용하는 것 보다 개발 속도의 이점이 있을 것 같습니다.
그리고 학습할만한 관련 자료들이 더 풍부하다는 점도 고려했습니다.

## 상태관리

현재 App.jsx에 공통된 상태들이 몰려있는데(물론 추후 page 컴포넌트나 다른 방식으로 App.jsx에서 분리 예정입니다)
상태관리 라이브러리 없이 어떤 식으로 상태를 비지니스 로직에서 분리해야 할지 고민중입니다.

# 📍 덴

## 고민

React와 styled-component가 아직 익숙하지 않아서, 컴포넌트 분리를 어떤 식으로 진행하면 좋을지 고민이 됩니다.

# 📍 시저

## 고민

드롭다운이 총 세곳에서 각각 비슷하지만 다른 모양으로 작동합니다.
드롭다운 바디의 각 아이템들 모양이 살짝씩 다릅니다.
드롭다운 바디의 각 아이템들을 클릭했을 때의 핸들러또한 드롭다운 컴포넌트를 사용할 때마다 바뀌어야 합니다.
이런 다른 점들을 고려하여 어떤 방식으로 재사용이 가능한 드롭다운으로 만들 수 있을지를 고민 중입니다.

2023-05-13 16:32 UTC, Jerome-Yoo commented
## 고민
> React와 styled-component가 아직 익숙하지 않아서, 컴포넌트 분리를 어떤 식으로 진행하면 좋을지 고민이 됩니다.
- styled-component는 숙련되고 나면 트러블슈팅여부와는 별개로 일반 html 태그를 쓰는 느낌이 될 거예요. 걱정하지 말고 일단 한 파일에 짱박아보자 라는 마인드로 시작해보면 어떨까요? 코드를 작성하다가 불편한 감정이 들면 그때 분리를 시도해도 늦지 않습니다. 한 번에 잘할 수는 없는지라 완벽성을 추구하지 말았으면 좋겠어요.

> 숙련도가 높지 않은 상황에서 재사용성과, 범용성 키워드에 대한 고려를 하고 구현할지, 일단 학습과 구현을 병행 하면서 점차 수정해 나갈지 고민됩니다.
- 제가 너무 큰 허들을 드렸던 것 같군요. 어떻게 컴포넌트를 만드는 것이 좋냐? 에 대한 질문답변의 과정에서 재사용성과 범용성이라는 키워드를 드렸던 것이구요, 주제가 너무 어렵게 다가온다 재사용성과 범용성이라는 키워드는 제가 리뷰과정에서 납득되지 않는 포인트들을 전달드리는 형태를 기반으로 해서 학습해보는 것이 좋을 것 같다는 생각이 듭니다. 일단 개발하는 것 자체가 어려운 것이니 할 수 있는 방향으로 하는게 맞겠다는 생각이 들어요.

> 드롭다운이 총 세곳에서 각각 비슷하지만 다른 모양으로 작동합니다. 드롭다운 바디의 각 아이템들 모양이 살짝씩 다릅니다. 드롭다운 바디의 각 아이템들을 클릭했을 때의 핸들러또한 드롭다운 컴포넌트를 사용할 때마다 바뀌어야 합니다. 이런 다른 점들을 고려하여 어떤 방식으로 재사용이 가능한 드롭다운으로 만들 수 있을지를 고민 중입니다.

- 지금의 고민을 명세화하면 두가지 정도가 나뉘는 것 같아요.  
  1. 드롭다운 컴포넌트를 사용할 때마다 핸들러 함수가 바뀌어야 한다. 
  2. 드롭다운 컴포넌트의 바디 영역이 사용할 때마다 달라져야 한다.

1번 고민은 왜 나오게 되었을까요? 올려주셨던 드랍다운 컴포넌트를 보면 핸들러 함수가 없어서 잘 보이지는 않지만.. 아마 핸들러 함수를 드롭다운 컴포넌트 내부에서 선언하려고 했기 때문이 아닐까요. 그럼 
- 핸들러1을 사용하는 드랍다운1, 
- 핸들러2를 사용하는 드랍다운2, 
- 핸들러3을 사용하는 드랍다운3  
이런식으로 드랍다운 컴포넌트가 많아지게 될 것 같군요.   

요것을 가만히 놓고 생각해보면, 이렇게 바꿔볼 수 있을 것 같아요.
- 핸들러 (1,2,3)을 사용하는 드랍다운 (1,2,3)
드랍다운의 모양이 다르다는 2번 고민 명세도 있긴 하지만, 드랍다운이 똑같다고 가정하면, 이렇게 정리해볼 수 있겠군요.
- 핸들러 (1,2,3)을 사용하는 드랍다운
그렇다면, 드랍다운이라는 컴포넌트는 핸들러를 본인이 선언하는게 아니라 핸들러만 전달받아서 실행만 해주면 되지 않을까? 하는 생각을 해볼 수 있을 것 같아요.


제가 이 텍스트에서 하고 싶은 말은
- 재사용성을 고려할 때에는 어디서든 동일한 인터페이스로 작동해야한다 를 기본으로 깔고 가야한다.
예요.
사용처에서는 대강 이런 느낌으로 해보면 되지 않을까요?   
```jsx
<Dropdown handleSelect={핸들러함수1,2,3}  />
// cf) 핸들러함수 props의 위치가 꼭 드랍다운이 시작하는 지점일 필요는 없어요.
```

2번 고민은 드랍다운의 UI가 다르기 때문에 당연히 있을 수밖에 없는 고민이라고 여겨져요.  
- 사용처마다 바디영역이 다르고, 이것 사이에 공통점이나 묶을 수 있는 규칙이 없다면 바디를 2개 3개 만들면 됩니다. 필요한 순간에 필요한 바디를 쓰면 되지요.
너무 깊게 고민하지 마서용 ㅎㅎ

2023-05-13 17:34 UTC, Jerome-Yoo requested changes
첫주 작업 고생하셨습니다~
이번에 코멘트 앞에 다음의 prefix가 붙어있습니다. 각각의 역할은 다음과 같아요.
- 적극 : 개선이 되어야 합니다.
- 제안 : 개선을 해보면 어떨까요? 하지 않아도 무방하긴 해요.
- 질문 : 잘 몰라서 그러는데 답변을 부탁드려요.

적극 코멘트를 집중해서 다뤄주시고 나머지 코멘트는 커뮤니케이션을 통해 다루면 좋을 것 같습니다.
이번 작업의 경우는 방향을 맞춰야하는 지점이 있어야 하기 때문에 Approve를 드렸는데요. 다음 개발작업부터는 적극 코멘트가 달리는경우 RequestChanges를 드리고 한번에 머지가 되지 않도록 할 예정이에요. 해소에 대해서는 RC의 해소에 대해서는 ASAP로 리뷰 대응할 수 있도록 할테니 참고해주시면 감사하겠습니다~

전체 차원에서 이번 PR을 보고 드리고 싶은 질문은 다음과 같아요.
Q. <Styled... /> 는 의미가 있는 네이밍일까?
Q. <StyledDiv />는 팀원을 설득할 수 있는 네이밍인가?
Q. <Container /> 라는 컴포넌트 네이밍 맥락에는 어떤 맥락이 담겨야 할까?
Q. 중복되는 스타일 코드를 어떻게 모듈화 할 수 있을까?
Q. 하드 코딩된 스타일 코드를 재사용하려면 무엇을 고려해야할까?

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/public/index.html
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
[적극]
이번 PR에서 `public 디렉토리`에 `favicon`, `logo192`, `manifest.json`이 삭제된 상황인 것 같군요. 
실행할때 네트워크탭에서 에러가 떨어지지 않던가요?
모든 행위에는 이유가 갖춰져야 한다고 생각하는데요, 왜 삭제가 되었는지 궁금합니다.
- 삭제를 하는게 맞다면, 해당 코드의 수정이 필요한 상황으로 여겨지는군요.
- 삭제를 하는게 맞지 않다면, 회고 차원에서 왜 이런 행위가 있었는지 서로 커뮤니케이션하는 것이 필요해보여요.

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/public/index.html
[제안]
주석은 필요한 내용이 아니면, 지워주세요~

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/components/DropDown.jsx
> +  margin-top: 0.8rem;
[제안]
이런 주석은 구분을 위해 `//TODO :` 로 시작하는게 어떨까요? 

fyi) 의외로 주석에 대한 포맷팅이 아주아주 중요하답니다. 검색해야하는데 내용이 생각안나면, 검색이 안되는 상황이 벌어지기 때문이죠.
fyi) https://ux.stories.pe.kr/184

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +  });
이 부분이 서로 공유하는 영역이 되는 군요.  좋은 판단입니다 👍  이런식으로 하나하나 정의해나가면 되는거지요

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +  });
[질문]
counts를 다 묶어서 처리하겠다는 생각은 너무 좋은데요. `setCounts(카운트 number 값)` 이렇게는 처리가 안되게 되니까,
매번 업데이트를 할 때마다 `setCounts({...counts, 업데이트하려는Count: number})` 이렇게 이전 맥락의 counts를 넣어줘야 한다는 불편함이 생기는 것 같아요. 이걸 어떻게 해소해볼 수 있을까요?

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/components/IssueStatusButtons.jsx
> +  const { openedIssueCount, closedIssueCount } = props;
[적극]
컴포넌트에 필요한 property값을 내려받는데에 props라는 이름으로 받는 것은 사용하는 시점에서 어려움이 있을 것 같군요.
지금은 모든 프로젝트를 0-100으로 개발하고 있으니 기억에 의해 관리가 될텐데요, 규모가 커지면 커질수록 부담이 있을거예요.

만약 제가 `IssueStatusButtons` 를 사용해야한다면, props의 인터페이스를 매번 확인해야만 하는 의무가 생기고, 맥락을 알아야지만 props를 변경할 수 있다는 점에서 걱정이 먼저 될 것 같아요. 
props에 담겨있는 것을 처음 내려줄때부터 풀어서 openedIssueCount, closedIssueCount 를 직접 내려받는 편이 낫지 않나 싶습니다.

[제안]
아, 만약 count정보를 묶어서 보내주고 싶었다면 `issueCounts` 라는 이름으로 바꿔서 내려주는 것은 어떨까 싶어요.

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/components/IssueTable.jsx
> +      <IssueStatusButtons props={props} />
fyi) `<IssueStatusButtons props={props} />`를 `<IssueStatusButtons {...props} />`로 바꿔주면 전개해서 property가 내려가는 효과를 갖습니다

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/components/TableToolBar.jsx
> +  const { children } = props;
fyi) `const TableToolBar = ({ children }) => { ... }` 도 가능해보이는군요~

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/components/GlobalStyles.jsx
> +`;
스타일관련해서 리세팅을 하려는 것이 목표이시죠?
[질문] 대부분 커뮤니케이션에 의해 논의된 것이라 생각하는데 하나 궁금한 점이 있어요. `html { font-size: 62.5% }` 은 어떻게 작동되는 것일까요?

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/components/DropDown.jsx
> +  margin-top: 0.8rem;
[적극]
어떤 부분은 rem으로 정의가 되어있고 어떤 부분은 px로 정의되어 있는데요. 전체 프로젝트 차원에서 이 부분은 맞춰주셔요.

fyi. 저는 어떤 전략을 취하냐면요, 바로 생각이 직관적으로 떠오르는 형태의 값으로 주로 작성하는 편입니다.

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/components/FilterBar.jsx
> +const StyledFilterButton = styled(FilterButton)`
오 상속된 스타일드컴포넌트 👍

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/src/components/FilterButton.jsx
> +  }, []);
[제안]
완성되지 못한 코드가 들어가 있는 것 같은데요, 이런 부분은 왜 작성하고자 했는지를 맥락을 담아서 주석으로 남겨주세요~
ex) //FIXME: 클릭이벤트를 핸들링해야함

2023-05-13 17:34 UTC, Jerome-Yoo commented on fe/.eslintrc.js
(급하지 않음) 프로젝트가 끝나기 전에 반나절정도 날잡아서 해당 프로퍼티들이 어떤 역할을 하는지 학습해보시는 것은 어떨까요~

2023-05-13 17:34 UTC, Jerome-Yoo approved these changes
첫주 작업 고생하셨습니다~
이번에 코멘트 앞에 다음의 prefix가 붙어있습니다. 각각의 역할은 다음과 같아요.
- 적극 : 개선이 되어야 합니다.
- 제안 : 개선을 해보면 어떨까요? 하지 않아도 무방하긴 해요.
- 질문 : 잘 몰라서 그러는데 답변을 부탁드려요.

적극 코멘트를 집중해서 다뤄주시고 나머지 코멘트는 커뮤니케이션을 통해 다루면 좋을 것 같습니다.
이번 작업의 경우는 방향을 맞춰야하는 지점이 있어야 하기 때문에 Approve를 드렸는데요. 다음 개발작업부터는 적극 코멘트가 달리는경우 RequestChanges를 드리고 한번에 머지가 되지 않도록 할 예정이에요. 해소에 대해서는 RC의 해소에 대해서는 ASAP로 리뷰 대응할 수 있도록 할테니 참고해주시면 감사하겠습니다~

전체 차원에서 이번 PR을 보고 드리고 싶은 질문은 다음과 같아요.
Q. <Styled... /> 는 의미가 있는 네이밍일까?
Q. <StyledDiv />는 팀원을 설득할 수 있는 네이밍인가?
Q. <Container /> 라는 컴포넌트 네이밍 맥락에는 어떤 맥락이 담겨야 할까?
Q. 중복되는 스타일 코드를 어떻게 모듈화 할 수 있을까?
Q. 하드 코딩된 스타일 코드를 재사용하려면 무엇을 고려해야할까?

2023-05-13 17:34 UTC, Jerome-Yoo approved these changes
첫주 작업 고생하셨습니다~
이번에 코멘트 앞에 다음의 prefix가 붙어있습니다. 각각의 역할은 다음과 같아요.
- 적극 : 개선이 되어야 합니다.
- 제안 : 개선을 해보면 어떨까요? 하지 않아도 무방하긴 해요.
- 질문 : 잘 몰라서 그러는데 답변을 부탁드려요.

적극 코멘트를 집중해서 다뤄주시고 나머지 코멘트는 커뮤니케이션을 통해 다루면 좋을 것 같습니다.
이번 작업의 경우는 방향을 맞춰야하는 지점이 있어야 하기 때문에 Approve를 드렸는데요. 다음 개발작업부터는 적극 코멘트가 달리는경우 RequestChanges를 드리고 한번에 머지가 되지 않도록 할 예정이에요. 해소에 대해서는 RC의 해소에 대해서는 ASAP로 리뷰 대응할 수 있도록 할테니 참고해주시면 감사하겠습니다~

전체 차원에서 이번 PR을 보고 드리고 싶은 질문은 다음과 같아요.
Q. <Styled... /> 는 의미가 있는 네이밍일까?
Q. <StyledDiv />는 팀원을 설득할 수 있는 네이밍인가?
Q. <Container /> 라는 컴포넌트 네이밍 맥락에는 어떤 맥락이 담겨야 할까?
Q. 중복되는 스타일 코드를 어떻게 모듈화 할 수 있을까?
Q. 하드 코딩된 스타일 코드를 재사용하려면 무엇을 고려해야할까?

2023-05-13 17:34 UTC, Jerome-Yoo approved these changes
첫주 작업 고생하셨습니다~
이번에 코멘트 앞에 다음의 prefix가 붙어있습니다. 각각의 역할은 다음과 같아요.
- 적극 : 개선이 되어야 합니다.
- 제안 : 개선을 해보면 어떨까요? 하지 않아도 무방하긴 해요.
- 질문 : 잘 몰라서 그러는데 답변을 부탁드려요.

적극 코멘트를 집중해서 다뤄주시고 나머지 코멘트는 커뮤니케이션을 통해 다루면 좋을 것 같습니다.
이번 작업의 경우는 방향을 맞춰야하는 지점이 있어야 하기 때문에 Approve를 드렸는데요. 다음 개발작업부터는 적극 코멘트가 달리는경우 RequestChanges를 드리고 한번에 머지가 되지 않도록 할 예정이에요. 해소에 대해서는 RC의 해소에 대해서는 ASAP로 리뷰 대응할 수 있도록 할테니 참고해주시면 감사하겠습니다~

전체 차원에서 이번 PR을 보고 드리고 싶은 질문은 다음과 같아요.

> Q. <Styled... /> 는 의미가 있는 네이밍일까?  
> Q. <StyledDiv />는 팀원을 설득할 수 있는 네이밍인가?  
> Q. <Container /> 라는 컴포넌트 네이밍 맥락에는 어떤 맥락이 담겨야 할까?  
> Q. 중복되는 스타일 코드를 어떻게 모듈화 할 수 있을까?  
> Q. 하드 코딩된 스타일 코드를 재사용하려면 무엇을 고려해야할까?

2023-05-13 17:47 UTC, Jerome-Yoo commented on fe/public/index.html
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
다른 팀들 PR구경을 하고 왔는데요, 마침 비슷한 고민 내용이 있어서 링크 달아봅니다. 
https://github.com/codesquad-members-2023/issue-tracker/pull/14#discussion_r1192956661

2023-05-13 17:49 UTC, Jerome-Yoo commented on fe/.eslintrc.js
다른 팀에서도 비슷한 맥락의 리뷰가 있어서 또 가져와봤습니다.
같이 고민을 해보시는 것도 좋을 것 같네요
https://github.com/codesquad-members-2023/issue-tracker/pull/12#discussion_r1192972740

2023-05-13 18:02 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +  });
[좀 더 거대한 질문]
과연 카운트 값은 실제로 상태로서 다뤄지기에 적절할까요?
이 질문을 해소하기 위해 드리는 작은 질문
- 열린 이슈와 닫힌 이슈는 어떻게 받기로 BE와 논의하셨나요?
- 모든 데이터를 상태로서 다뤄야할까요? 
  - fyi) 파생상태 : https://itchallenger.tistory.com/487 
  - fyi) vue.js에서는 이 주제를 computed property라는 이름으로 다루고 있어요.
  - hint) 어디선가 이슈가 모여있는 데이터가 있다면, 그것을 활용해서 이슈 카운트로 다뤄져야 하지 않을까요?

2023-05-13 21:26 UTC, zlx454545 commented on fe/public/index.html
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
넵 네트워크 에러가 있었는데 크게 고려하지 않았던 부분입니다. 
주말에는 각자 공부를 하기로 한 상태라 덴의 의견을 정확히는 모르지만 아마도 지우는 방향으로 가지 않을까..? 싶습니다.

다음주에 함께 수정해서 다시 PR 날리도록 하겠습니다.

2023-05-13 21:36 UTC, zlx454545 commented on fe/src/App.jsx
> +  });
카운트들이 derived state인건 인지하고 있었습니다.

이 부분에서 저희도 굉장히 고민이 많았는데, 
오픈된 이슈를 클릭할때 이슈 리스트에는 오픈 상태의 이슈들만 보이게 되잖아요?

이 상황에서.. 오픈된 이슈가 1개고 닫힌 이슈가 만개일때 전체 이슈를 받아오면 쓸데없는 트래픽이 발생한다 라는 생각 때문에 

백엔드분들이랑 협의됐던 부분이 최소한의 트래픽으로 뷰에 그려질 데이터들만 딱 받자여서
오픈된 이슈를 클릭했을때 오픈된 이슈들만 받고 / 닫힌 이슈, 라벨, 마일스톤 등의 개수들은 단순 숫자로 받는 쪽으로 결정이 됐습니다.

사실 이 부분이 조금 저도 어색하다고 생각하는데 (오픈된 이슈를 클릭했을 때, 오픈 이슈에 대한 엔드포인트에서 오픈된 이슈 목록 뿐만 아니라 다른 카운트들이 오는게 restful하지도 않기도 해서,,)

트래픽이 낭비되더라도 매번 버튼을 클릭할때 모든 이슈, 라벨, 마일스톤에 대한 전체 데이터를 다시 fetching해오는게 더 합리적인 선택일지? 또는 더 자연스러운지? 의견을 여쭈고 싶습니다.

2023-05-13 21:45 UTC, zlx454545 commented on fe/src/components/GlobalStyles.jsx
> +`;
아 이 부분은 제가 거의 일방적으로(ㅎㅎ;) 이렇게 하자고 했던 부분인데요.

css강의를 듣다가 알게된 테크닉인데요.

1) 루트의 폰트 사이즈를 62.5%로 하게 되면 10px이 되어서
뭐 마진이나 이런 속성들이 20px로 주고 싶다면 2rem (=== 20px)과 같이 단순 무식하게 나누기 10해주면 되서 개발하는데 용이합니다.
2) 그럼 왜 또 rem이냐? 서비스 이용자 중에 폰트 크기를 확대해서 사용하는 경우 px로 스타일링 하면 확장된 폰트 크기에 대응을 못하지만, rem을 사용할 경우 이 부분이 대응이 된다고 학습하였습니다.

2023-05-13 21:47 UTC, zlx454545 commented on fe/src/components/DropDown.jsx
> +  margin-top: 0.8rem;
위의 답변과 이어지는 답변일것 같은데, 

만약 font-size: 62.5%를 두고 rem으로 스타일링 하는 데 빰빰이 별 문제가 없다고 의견을 주시면 아마도 rem으로 통일을 할 것 같습니다.

2023-05-13 22:06 UTC, zlx454545 commented on fe/src/App.jsx
> +  });
> [질문] counts를 다 묶어서 처리하겠다는 생각은 너무 좋은데요. `setCounts(카운트 number 값)` 이렇게는 처리가 안되게 되니까, 매번 업데이트를 할 때마다 `setCounts({...counts, 업데이트하려는Count: number})` 이렇게 이전 맥락의 counts를 넣어줘야 한다는 불편함이 생기는 것 같아요. 이걸 어떻게 해소해볼 수 있을까요?

아래와 같은 setter들을 count 갯수만큼 일일히 만드는 방법 외에는 당장은 생각 나는게 없습니다. 혹시 찾아볼 만한 키워드가 있을까요?

```
const set업데이트하려는Count = (new업데이트하려는Count) => {
    setCounts({
      ...counts,
      업데이트하려는Count: new업데이트하려는Count,
    });
  };
```

2023-05-14 08:14 UTC, sjuhan123 commented on fe/src/components/IssueStatusButtons.jsx
> +  const { openedIssueCount, closedIssueCount } = props;
가독성 등 여러 차원에서 이 부분은 앞으로의 개발에도 적극 반영하겠습니다.

> [제안]  
> 아, 만약 count정보를 묶어서 보내주고 싶었다면 issueCounts 라는 이름으로 바꿔서 내려주는 것은 어떨까 싶어요.

count 정보들 중에서 2개의 상태만 받아서 쓰는 상황이라, 변수명을 고민 중이었었는데, `issueCounts`도 고려해보겠습니다. 감사합니다!

2023-05-14 10:35 UTC, Jerome-Yoo commented on fe/public/index.html
> +    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
@zlx454545 네트워크에서 에러가 나는데 크게 고려하지 않으면 안되는 것이지요~
에러가 나면 일단 문제상황이라고 인지해주셨으면 좋겠어요~

2023-05-14 10:37 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +  });
> 아래와 같은 setter들을 count 갯수만큼 일일히 만드는 방법 외에는 당장은 생각 나는게 없습니다. 혹시 찾아볼 만한 키워드가 있을까요?
derived state인지라 상태로서 다루지 않는것이 베스트이긴 한데요, 일단 차치하고, 차라리 count마다 분리해서 상태를 다루는 것이 맥락을끊어낼 가장 확실한 방법이라 여겨져요.

2023-05-14 10:57 UTC, Jerome-Yoo commented on fe/src/components/GlobalStyles.jsx
> +`;
[찬성의견]
모든 유저의 디바이스를 고려하는 결정이군요 멋집니다! 
저는 그래서 몇 px이야? 에 대한 답변에 좀 더 유용하게 대응하기 위해 px을 쓰고는 합니다.

[반대의견]
웹접근성의 관점에서 rem의 사용이 분명 좋은 건 맞습니다만, 현실적으로 비즈니스를 고려한 결정을 해야하는 경우도 다분합니다. 정해진 시간 안에 모든 디바이스의 사정을 우리가 다 케어할 수는 없습니다. 다만, 어떤 상황까지는 우리가 반드시 챙겨야겠다의 결정은 내릴 수 있어요. 실제로 확대된 뷰에서 깨지는 스타일마다 또 처리해줘야하는 공수가 들어가겠지요. 적당한 선에서 지치지 않도록 타협을 보셨으면 좋겠군요.

2023-05-14 11:00 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +  });
> 트래픽이 낭비되더라도 매번 버튼을 클릭할때 모든 이슈, 라벨, 마일스톤에 대한 전체 데이터를 다시 fetching해오는게 더 합리적인 선택일지? 또는 더 자연스러운지? 의견을 여쭈고 싶습니다.
- 트래픽을 줄이는 것을 좀 더 중요하게 여기는 조직이라면, 그것에 부합한 결정을 해야한다고 생각하구요. 파생상태를 줄이는 것을 좀 더 중요하게 여기는 조직이라면, 그 결정을 따라야 한다고 생각해요. 만약 오버페칭을 줄이기 위해 API 수정을 할 수 있는 상황이라면 그것을 시도하는 것도 좋은 방법이겠습니다.

2023-05-14 11:02 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +  });
> 트래픽이 낭비되더라도 매번 버튼을 클릭할때 모든 이슈, 라벨, 마일스톤에 대한 전체 데이터를 다시 fetching해오는게 더 합리적인 선택일지? 또는 더 자연스러운지? 의견을 여쭈고 싶습니다.

- 실제로 낭비일까요? 예를 들어 이슈 하나를 close로 했다고 쳐봅시다. 그럼 보여지는 뷰에서는 close 이슈중 하나가 open으로 넘어가야하는 상황이겠죠? 그럼 결국 오픈이슈와 클로즈이슈 두개의 이슈 목록을 다시 받아와야 하는 상황이라고 이야기해볼 수 있지 않을까요?

2023-05-14 11:06 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +  });
> 따라서 매 클릭시 오직 개수만 필요할지라도
- 대부분 API가 모든 FE의 요구사항을 들어주지는 않습니다. 경험상 fetching이 1sec 미만으로 끝나면 실제로 큰 문제로 여기지는 않는 것 같아요.

2023-05-14 11:10 UTC, Jerome-Yoo commented
제가 머지를 했어야 하는 건가봐요? 다음에 Approve가 올라와있다면 직접 머지해주셔도 괜찮을 것 같습니다
일단 머지할게요 @sjuhan123 @zlx454545

2023-05-14 11:10 UTC, merged