Be
codesquad-members-2023/issue-tracker pull request #11
Opened 2023-05-12 02:29 UTC by lvalentine6

ss

2023-05-13 04:45 UTC, new-pow commented
> 이슈 수정이 안되어서 코멘트로 질문 부분 추가로 남겨놓습니다.
> 둘이 함게 고민하고 논의했던 부분은 이슈사항의 링크로 정리해두었습니다.

## 인프라
- 이번 미션에서 어느정도까지 학습하는 것이 좋을지? 지금의 구조는 
- 현재 webserver 역할을 할 EC2, was 역할을 할 EC2로 나누었습니다.
- github action으로 배포시 두개의 인스턴스에 필요한 리소스만 배포할 수 있는 방법이 있나요? 두개의 인스턴스에 배포하게 될 시, 서로 안쓰는 코드가 각각 올라가게 되는데 이부분에서 더 깔끔한 방법은 없을지 고민이 됩니다.

### 이미지 호스팅을 위해 S3 접근 EC2 결정 논의
- 노션 링크로 논의 과정을 간단하게 적어두었습니다.
- 지금의 개인적인 생각으로는 S3 put object 권한이 was에만 있는게 더 낫지 않을까 싶습니다.

## DB 모델링
- 전반적인 피드백이 필요합니다.
- issue 목록을 조회하거나 issue 상세 페이지 조회시 동시에 5개 테이블을 join하게 되는데, 성능 문제가 있지 않을까 우려됩니다. 인덱싱을 하는 것으로 해결 할 수 있을까요?

2023-05-13 16:45 UTC, jinan159 requested changes
안녕하세요 로이, 이린!
리뷰에 Jay입니다.

이번 리뷰에서는 일전에 말씀드렸던대로 Pn룰을 적용해서 코멘트를 드렸습니다.

- P1: 꼭 반영해주세요 (Request changes)
  - 중대한 오류, 버그 가능성을 내포하고 있는 경우
  - 리뷰 요청자는 요청을 반영하거나, 혹은 반영할 수 없는 이유를 설명해야합니다.
- P2: 웬만하면 반영해 주세요 (Comment)
  - 오류는 아니지만 성능 혹은 구조적으로 문제가될 수 있는 경우
  - 리뷰 요청자는 요청을 반영하거나, 혹은 반영할 수 없는 이유를 설명해야합니다.
- P3: 반영해도 좋고 넘어가도 좋습니다 (Approve)
  - 리뷰어의 사소한 의견으로 이에 대해 답변을 달아도 되고, 안달아도 괜찮습니다. (하지만 확인했다는 여부를 알리기 위한 이모지 정도만 달아주시면 감사하겠습니다.)

----

크게 DB 모델링과 이미지 호스팅에서 고민이 많으셨던 것 같아요.
이에 대해서 제가 아는 선에서 조언들 드릴게요.
(시간과 지식의 한계로 제가 조언 가능한 부분만 코멘트 남겼습니다😅)

# AWS

> -   이번 미션에서 어느정도까지 학습하는 것이 좋을지? 인프라 끝이 없네요...
> -   github action으로 배포시 두개의 인스턴스에 필요한 리소스만 배포할 수 있는 방법이 있나요? 두개의 인스턴스에 배포하게 될 시, 서로 안쓰는 코드가 각각 올라가게 되는데 이부분에서 더 깔끔한 방법은 없을지 고민이 됩니다.

일단 이 부분의 경우 FE 배포와 BE 배포를 분리하고싶으신 것으로 이해했습니다.
두 배포가 성격이 다르니 분리할 필요가 있으실 것 같은데 아래 링크를 참조하시면 될 것 같습니다.
https://docs.github.com/ko/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths

github action 에서 특정 path 가 변경되었을때만 실행시키거나, 특정 path 는 변경되어도 실행하지 않도록 하는 필터링 기능이 있는데 이를 활용하시면 될 것 같네요~

그리고 현재 서버를 어떻게 실행시키는지에 대한 정보는 없어서 아래처럼 진행된다고 가정하고 말씀드릴게요.

git push -> github action -> ec2 -> build -> jar file execute

현재 Github Action에서 소스코드를 모두 Instance 로 보내고, 거기서 빌드 하시기 때문인 것 같은데요.
Github Action 에서 빌드 후 실행에 꼭 필요한 파일만 Instance 로 보내시는것도 하나의 방법입니다.

## 이미지 호스팅

> - frontend - backend 역할이 나뉜 각각의 인스턴스에서 S3를 접속할 수 있게 해도 되는 것인가?
    - 이슈 이미지의 경우 이미지 업로드시 was에서 따로 검증할 필요가 없는 것 같다. 그러므로 webserver에서 직접 S2에 업로드하는 방법은 어떨까?
        - 회원만 이미지 업로드가 가능하도록 해야하는지?
        - webserver에서 S3 접근 키를 가지고 있게 되는데, 이 점이 괜찮을까?
    - 다만 프로필 이미지의 경우, 회원 본인 인증이 필요하므로 WAS에서 처리
>   - 그 외에 예상되는 취약점이 있는지?

일단 당연히 FE에서 S3에 접근 가능한 키를 가지고있는건 매우 매우 위험합니다.
(호눅스에게 물어보시면 기겁하실거에요 ㅋㅋㅋ)

이 경우 AWS S3 Presigned url 이라는 방식을 사용해볼 수 있습니다.
(https://docs.aws.amazon.com/ko_kr/AmazonS3/latest/userguide/PresignedUrlUploadObject.html)
하지만 약간의 러닝커브가 있을 수 있으니, FE와 잘 협의 하셔서 다른 기능을 모두 구현한 다음 이미지 업로드를 마지막에 구현하는것도 하나의 방법입니다.

# DB 모델링

- `issue_has_label` 테이블 관련
  일반적으로 테이블에 has 등의 동사는 들어가지 않는 것 같아요(경험상)
  하지만 issue 와 label 이 N:M 관계이니, 관계형 DB에서는 이 테이블이 필연적으로 생기는건 어쩔 수 없는 것 같습니다.
  
- 5개 테이블 join 하는것과 관련한 고민
  정말 좋은 고민이라고는 생각하지만, 일단은 현재 단계에서는 아직 깊이 고민할 단계는 아니라고 생각합니다.
  프로젝트를 시작할 단계에 결정하고 갈만한 정도라면 이미 데이터 양이나 트래픽이 어느정도 예상되는 서비스라면 가능한데요.
  그렇지 않은데 너무 많은 시간을 쏟는것은 사실 오버엔지니어링이 아닐까? 하고 생각할수도 있을 것 같아요.
  일단 인덱싱으로 임시 방편은 되고, 그 다음이 캐싱인데 캐싱으로 왠만하면 거의 해결이 됩니다.
  그리고 그 다음(샤딩 등)을 고민하는 순간이 오면 이미 거대한 서비스로 변모했을 것 이기 때문에 또 다른 상황이죠.
  
- count 컬럼 추가?
  관련하여 count 컬럼 추가는 흔히 사용되는 방법입니다.
  하지만 `milestone FK` + `status` + `issue_deleted` 이런 인덱스 조합은 추천하고싶지 않은 조합입니다.
  아시는것처럼 수정, 삭제시 인덱스를 다시 정렬해야하기 때문에 비용이 많이 드는 작업인데요.
  특히 status, issue_deleted 는 자주 바뀔 수 있는 항목이기 때문에 인덱스하기 좋은 컬럼은 아닙니다.
  
  - 이 방식 적용시 트리거 추가?
    트리거는 개인적으로 추천하고싶은 방식은 아닙니다.
    저는 마일스톤에 포함된 이슈들의 오픈/클로즈 상태별 개수를 변경하는건 '비즈니스 로직' 이라고 생각하는데요.
    이를 DB에 의존시키는건 좋은 방법이 아니라고 생각합니다.

- count 테이블 추가?
  이슈관리 서비스에서 이슈의 상태별 개수를 저장하기 위함이라면 테이블 보다는 컬럼을 만드는게 나은 것 같아요😅

현재 DB 설계는 잘 되어있다고 생각되는데요.
문서를 봤을때 두분이 고민하시는 부분이 다음과 같은 것 같아요.

- 이슈 목록 조회 : 이슈 n개 * 이슈의 라벨 m개
- 마일스톤 목록 조회 : 마일스톤 n개 * 각 마일스톤의 이슈 m개

이에 대해서 생각해보면 좋을 ㅇㅇ가지 관점을 말씀드리겠습니다.

1. '한방 쿼리' vs '여러번의 가벼운 쿼리'
'무거운 한방 쿼리' 보다 '여러번의 가벼운 쿼리'를 날려서 WAS에서 조합하는게 성능이 더 좋을 수 있습니다.

2.이슈나 마일스톤이 각각 100만개씩 있다고 해도, 페이징을 한다면 괜찮지 않을까?
보통 목록 조회시 마일스톤이나 이슈의 전체를 탐색하는 경우는 드물겠죠.
목록 조회시 페이징을 적용하면 문제점들이 개선될 수 있는지 한번 생각해보시는것도 좋습니다.

----

DB나 S3 저장 관련되서 고민하신점들을 문서로 잘 남겨주신게 인상깊네요 :)
공유해주신 덕분에 이슈를 파악하는데 많은 도움이 되었습니다 :)

제 짧은 경험과 지식을 바탕으로 여러가지를 말씀드렸는데요.
제가 말한 방법들이 모두 정답은 아닐거고, 제가 아는 방법들 중 가장 나은 방법입니다.
그러니 틀렸거나, 더 좋은 방법이 있을 수 있으니 참고해주시면 좋을 것 같습니다.

이번주도 고생하셨습니다~!

2023-05-13 16:45 UTC, jinan159 commented on .gitignore
> +### frontend ###
gitignore 파일을 fe, be가 같이 만드셨군요~

p3)
공통된 파일들을 관리하신다면 프로젝트 루트에 두고 관리해도 괜찮겠지만, 
프로젝트를 보니 'frontend', 'backend' 디렉토리로 나누어놓으셨더라구요~

이련 경우는 각 디렉토리에서 gitignore 파일을 만들어서 관리하는 방법도 있습니다 :)

2023-05-13 16:45 UTC, jinan159 commented on backend/build.gradle
> +    developmentOnly 'org.springframework.boot:spring-boot-devtools'
p3)
devtools 의존성을 어떤 목적으로 추가하셨는지 궁금하네요~

2023-05-13 16:45 UTC, jinan159 commented on backend/src/main/java/com/team6/issue_tracker/cloud/ImageHostContorller.java
> +public interface ImageHostContorller {
p3)
요 클래스는 추후 어떤 목적으로 사용될 예정일까요?

추측으로는 S3가 아닌 다른 저장소로 바뀌는 경우를 위한 컨트롤러 인퍼테이스를 두시려고한게 아닐까 생각되는데요.
이 관점에서 말씀드리자면 어딜 추상화하는게 좋을까 하는 고민이 드신다면
`바뀌는 부분`과 `바뀌지 않는 부분`을 구분해보고, 바뀌는 부분을 추상화 하시는게 좋습니다.
(제가 말한 이 부분은 토비의 스프링에서 템플릿 콜백 패턴의 설명에 나오는 부분이니 시간나실때 한번 보시는걸 추천드려요. 템플릿 콜백 패턴 관련 링크 : https://www.baeldung.com/spring-framework-design-patterns#1-templates-amp-callbacks)

만약 이미지 저장소와의 연동을 추상화 하고싶으셨다면, 이러한 관점에서 한번 고민해보시는걸 추천드립니다.

2023-05-13 16:45 UTC, jinan159 commented on backend/src/main/java/com/team6/issue_tracker/cloud/S3ImageHostService.java
> +    }
이건 정말 TMI 인데요.
구현해야하는 부분인 경우에는 TODO 주석을 활용하는것도 괜찮은 방법입니다.
IDE 에서 TODO 주석이 처리된 부분을 따로 모아서 보여주기도하거든요~

2023-05-13 16:45 UTC, jinan159 commented on backend/src/main/java/com/team6/issue_tracker/cloud/S3ImageHostService.java
> +    public MultifileInfo upload(MultipartFile file, Directory directory) throws IOException {
p2)
파일을 업로드 받을때는 용량제한을 두거나 정해진 확장자만 받도록 하는게 좋습니다 :)

2023-05-13 16:45 UTC, jinan159 commented on backend/build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-ui:1.6.9'
Swagger 를 사용하기로 결정하셨군요~

흔히 Swagger, Spring Rest Docs 중에 하나를 쓰는 경우가 많은데요.
두분이 Swagger를 사용하기로 결정하신 이유가 궁금하네요~
(단순 궁금증입니다)

2023-05-13 16:45 UTC, jinan159 commented on backend/src/main/java/com/team6/issue_tracker/cloud/S3ImageHostService.java
> +        MultifileToFileConvertor.convert(file)
MultifileToFileConvertor 구현을 보니 로컬에 파일을 한번 저장하고, 이 파일을 다시 읽어서 s3로 저장하는 흐름인 것 같네요.

p2)
보통 IO들 중에서 가장 느린 IO로 손꼽히는게 Disk IO인데요.
이 이미지 저장 기능에서는 2번이나 일어나고있군요.

지금 우선순위로 개발해야하는 기능들을 모두 개발하시고 나서, 나중에 시간이 남으면 이 부분을 어떻게 개선할 수 있을지 한번 고민해봐주세요~!

2023-05-13 16:45 UTC, jinan159 commented on backend/src/main/java/com/team6/issue_tracker/config/SwaggerConfig.java
> +                        .version("v0.0.1"));
이건 그냥 지나가다 생각나서 언급합니다.

p3)
아실수도 있지만, 혹시 모르신다면 `유의적 버전(Sementic Versioning)`에 대해 한번 간단히 살펴봐주세요~
(이 부분이 이상하거나 잘못되었다는 코멘트는 아닙니다!)

2023-05-13 16:45 UTC, jinan159 commented on backend/src/main/java/com/team6/issue_tracker/member/FooController.java
> +public class FooController {
요 컨트롤러는 이름이 'FooController' 이군요.
기능들을 보면 member 관련된 데이터를 내려주는 더미 컨트롤러처럼 보이네요.
FE 분이 연동해볼 수 있도록 미리 만들어두신 것 같네요👍

p3)
다만 더미 컨트롤러가 맞다면, FooController 보다는 더 직관적인 네이밍이 필요할 것 같습니다 :)
(물론 잠시 쓰고 사라질 녀석이라 이름이 크게 중요하지 않을 수는 있겠지만요 😅)

2023-05-13 16:45 UTC, jinan159 commented on backend/src/main/java/com/team6/issue_tracker/member/domain/dto/MemberTestResponse.java
> +@Setter
p2)
대부분의 객체들에 Setter를 습관적으로 붙이시는 것 같은데요.
요즘은 왠만하면 불변객체로 선언하고, 정말 꼭 필요한 부분만 setter를 열어주는 추세입니다.

불변객체 vs 가변객체의 차이와 장단점, 왜 요즘 불변객체를 사용하는 추세인지 한번 찾아보시는걸 추천드립니다~!

2023-05-13 16:45 UTC, jinan159 approved these changes
안녕하세요 로이, 이린!
리뷰에 Jay입니다.

이번 리뷰에서는 일전에 말씀드렸던대로 Pn룰을 적용해서 코멘트를 드렸습니다.

- P1: 꼭 반영해주세요 (Request changes)
  - 중대한 오류, 버그 가능성을 내포하고 있는 경우
  - 리뷰 요청자는 요청을 반영하거나, 혹은 반영할 수 없는 이유를 설명해야합니다.
- P2: 웬만하면 반영해 주세요 (Comment)
  - 오류는 아니지만 성능 혹은 구조적으로 문제가될 수 있는 경우
  - 리뷰 요청자는 요청을 반영하거나, 혹은 반영할 수 없는 이유를 설명해야합니다.
- P3: 반영해도 좋고 넘어가도 좋습니다 (Approve)
  - 리뷰어의 사소한 의견으로 이에 대해 답변을 달아도 되고, 안달아도 괜찮습니다. (하지만 확인했다는 여부를 알리기 위한 이모지 정도만 달아주시면 감사하겠습니다.)

----

크게 DB 모델링과 이미지 호스팅에서 고민이 많으셨던 것 같아요.
이에 대해서 제가 아는 선에서 조언들 드릴게요.
(시간과 지식의 한계로 제가 조언 가능한 부분만 코멘트 남겼습니다😅)

# AWS

> -   이번 미션에서 어느정도까지 학습하는 것이 좋을지? 인프라 끝이 없네요...
> -   github action으로 배포시 두개의 인스턴스에 필요한 리소스만 배포할 수 있는 방법이 있나요? 두개의 인스턴스에 배포하게 될 시, 서로 안쓰는 코드가 각각 올라가게 되는데 이부분에서 더 깔끔한 방법은 없을지 고민이 됩니다.

일단 이 부분의 경우 FE 배포와 BE 배포를 분리하고싶으신 것으로 이해했습니다.
두 배포가 성격이 다르니 분리할 필요가 있으실 것 같은데 아래 링크를 참조하시면 될 것 같습니다.
https://docs.github.com/ko/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths

github action 에서 특정 path 가 변경되었을때만 실행시키거나, 특정 path 는 변경되어도 실행하지 않도록 하는 필터링 기능이 있는데 이를 활용하시면 될 것 같네요~

그리고 현재 서버를 어떻게 실행시키는지에 대한 정보는 없어서 아래처럼 진행된다고 가정하고 말씀드릴게요.

git push -> github action -> ec2 -> build -> jar file execute

현재 Github Action에서 소스코드를 모두 Instance 로 보내고, 거기서 빌드 하시기 때문인 것 같은데요.
Github Action 에서 빌드 후 실행에 꼭 필요한 파일만 Instance 로 보내시는것도 하나의 방법입니다.

## 이미지 호스팅

> - frontend - backend 역할이 나뉜 각각의 인스턴스에서 S3를 접속할 수 있게 해도 되는 것인가?
    - 이슈 이미지의 경우 이미지 업로드시 was에서 따로 검증할 필요가 없는 것 같다. 그러므로 webserver에서 직접 S2에 업로드하는 방법은 어떨까?
        - 회원만 이미지 업로드가 가능하도록 해야하는지?
        - webserver에서 S3 접근 키를 가지고 있게 되는데, 이 점이 괜찮을까?
    - 다만 프로필 이미지의 경우, 회원 본인 인증이 필요하므로 WAS에서 처리
>   - 그 외에 예상되는 취약점이 있는지?

일단 당연히 S3에서 접근 가능한 키를 가지고있는건 매우 매우 위험합니다.
(호눅스에게 물어보시면 기겁하실거에요 ㅋㅋㅋ)

이 경우 AWS S3 Presigned url 이라는 방식을 사용해볼 수 있습니다.
(https://docs.aws.amazon.com/ko_kr/AmazonS3/latest/userguide/PresignedUrlUploadObject.html)
하지만 약간의 러닝커브가 있을 수 있으니, FE와 잘 협의 하셔서 다른 기능을 모두 구현한 다음 이미지 업로드를 마지막에 구현하는것도 하나의 방법입니다.

# DB 모델링

- `issue_has_label` 테이블 관련
  일반적으로 테이블에 has 등의 동사는 들어가지 않는 것 같아요(경험상)
  하지만 issue 와 label 이 N:M 관계이니, 관계형 DB에서는 이 테이블이 필연적으로 생기는건 어쩔 수 없는 것 같습니다.
  
- 5개 테이블 join 하는것과 관련한 고민
  정말 좋은 고민이라고는 생각하지만, 일단은 현재 단계에서는 아직 깊이 고민할 단계는 아니라고 생각합니다.
  프로젝트를 시작할 단계에 결정하고 갈만한 정도라면 이미 데이터 양이나 트래픽이 어느정도 예상되는 서비스라면 가능한데요.
  그렇지 않은데 너무 많은 시간을 쏟는것은 사실 오버엔지니어링이 아닐까? 하고 생각할수도 있을 것 같아요.
  일단 인덱싱으로 임시 방편은 되고, 그 다음이 캐싱인데 캐싱으로 왠만하면 거의 해결이 됩니다.
  그리고 그 다음(샤딩 등)을 고민하는 순간이 오면 이미 거대한 서비스로 변모했을 것 이기 때문에 또 다른 상황이죠.
  
- count 컬럼 추가?
  관련하여 count 컬럼 추가는 흔히 사용되는 방법입니다.
  하지만 `milestone FK` + `status` + `issue_deleted` 이런 인덱스 조합은 추천하고싶지 않은 조합입니다.
  아시는것처럼 수정, 삭제시 인덱스를 다시 정렬해야하기 때문에 비용이 많이 드는 작업인데요.
  특히 status, issue_deleted 는 자주 바뀔 수 있는 항목이기 때문에 인덱스하기 좋은 컬럼은 아닙니다.
  
  - 이 방식 적용시 트리거 추가?
    트리거는 개인적으로 추천하고싶은 방식은 아닙니다.
    저는 마일스톤에 포함된 이슈들의 오픈/클로즈 상태별 개수를 변경하는건 '비즈니스 로직' 이라고 생각하는데요.
    이를 DB에 의존시키는건 좋은 방법이 아니라고 생각합니다.

- count 테이블 추가?
  이슈관리 서비스에서 이슈의 상태별 개수를 저장하기 위함이라면 테이블 보다는 컬럼을 만드는게 나은 것 같아요😅

현재 DB 설계는 잘 되어있다고 생각되는데요.
두분이 고민하신 부분들은 궁극적으로 보면 '한방 쿼리'로 해결하려고 해서 그런게 아닐까 조심스레 생각해봅니다.
'무거운 한방 쿼리' 보다 '가벼운 여러번 쿼리'가 성능이 더 좋을 수 있거든요.

예를 들어 마일스톤의 정보를 가져와야 한다.
- 마일스톤 정보 + 이슈의 상태별 개수 정보 를 한방쿼리로 하려면 조인을 여러번...
  - '마일스톤 정보 1번 조회', '이슈의 상태별 개수 조회' 이 둘을 was에서 조합해서 반환하는 방법도 있을 것 같아요.

제 짧은 경험과 지식을 바탕으로 여러가지를 말씀드렸는데요.
제가 말한 방법들이 모두 정답은 아닐거고, 제가 아는 방법들 중 가장 나은 방법입니다.
그러니 틀렸거나, 더 좋은 방법이 있을 수 있으니 참고해주시면 좋을 것 같습니다.

이번주도 고생하셨습니다~!

2023-05-13 16:47 UTC, merged

2023-05-13 16:49 UTC, jinan159 commented
Approve 를 누른다는게 실수로 Change request 를 눌렀네요;
시간나실때 천천히 코멘트 확인해주세요~

2023-05-14 00:52 UTC, jinan159 commented on backend/src/main/java/com/team6/issue_tracker/member/domain/Member.java
> +    private Long idx;
p2)
그러고보니 DB member테이블의 idx 컬럼 타입은 INT로 잡으셨는데, 멤버 객체의 idx는 long 이더라구요~
한가지 통일해주시는게 좋을 것 같아요.

2023-05-15 02:07 UTC, new-pow commented on backend/build.gradle
> +    developmentOnly 'org.springframework.boot:spring-boot-devtools'
앗 습관처럼 추가해두었는데, 로이랑 상의하여 삭제하기로 하였습니다.

2023-05-15 02:10 UTC, new-pow commented on backend/src/main/java/com/team6/issue_tracker/cloud/S3ImageHostService.java
> +    public MultifileInfo upload(MultipartFile file, Directory directory) throws IOException {
이미지 호스팅을 3주차에 구현 하려고하는데, 그 때 더 보완하도록 하겠습니다.

2023-05-15 02:14 UTC, new-pow commented on backend/src/main/java/com/team6/issue_tracker/cloud/S3ImageHostService.java
> +        MultifileToFileConvertor.convert(file)
남겨주신 내용은 Trouble shooting issue로 기록해두고, 구현시 개선하도록 해보겠습니다.

2023-05-15 02:20 UTC, lvalentine6 commented on backend/src/main/java/com/team6/issue_tracker/member/domain/Member.java
> +    private Long idx;
mysql 데이터 타입을 BIGINT로 변경하였습니다. ⭐

2023-05-20 16:20 UTC, new-pow commented on backend/build.gradle
> +    implementation 'org.springdoc:springdoc-openapi-ui:1.6.9'
- Swagger가 API 테스트에 유용하고, 적용이 쉽다고 판단하여 선택했습니다.
- Spring Rest Docs는 문서화에 더 특화된 것 같다고 생각했습니다.