[TEAM-05][BE : NINO,고뭉남] Issue-Tracker 2주차 PR
codesquad-members-2023/issue-tracker pull request #37
Opened 2023-05-19 02:53 UTC by ninaaano

안녕하세요 산토리! 한주동안 잘 지내셨나요?
이번주는 학습하느라 바빠서 크게 구현한 게 없는 것 같습니다... 
인프라 구조 그리면서 고민을 많이했는데 아직 잘 모르겠어요ㅠㅠ

------

- 2주차 마일스톤 💎
[2주차 마일스톤](https://github.com/codesquad-members-2023-group5/issue-tracker/milestone/2)

------

### 질문

-------

## 니노

### 인프라 구조 설계

<img width="529" alt="인프라구조설계" src="https://github.com/codesquad-members-2023/issue-tracker/assets/95615105/bea443f5-2bad-454c-a89a-63c0f724c930">

### 자동배포과정

<img width="517" alt="배포과정" src="https://github.com/codesquad-members-2023/issue-tracker/assets/95615105/5d520b37-00b5-40b1-8995-6b073f3f0963">

-------

## 고뭉남

2023-05-19 05:28 UTC, seyoung755 commented
한 주간 고생하셨습니다! 리뷰하기 전에 먼저 질문에 답변드릴게요!

- 인프라 구조를 이해하기로는 WAS는 public에, DB는 private subnet에 구축해주신 것 같고, DB 이중화 등의 이유로 private 망은 각각 다른 AZ마다 하나씩 만들어주신 것 같은데 맞을까요? 맞다면 세팅을 잘해주신 것 같습니다. 👍 
VPC의 IP 정보나 public, private subnet의 라우팅 테이블 규칙도 적어주셨다면 조금 더 좋을 것 같습니다. 인프라 구조를 그리는 툴이 많으니 그런걸 활용해보셔도 좋을 것 같습니다 ㅎㅎ
뭔가 구조가 헷갈린다면 클라이언트 <-> WAS, WAS <-> DB 간의 인바운드/아웃바운드 트래픽을 추적하면서 어떻게 통신이 흘러가는지 한번 되짚어보시는 것도 좋을 것 같습니다! 

구성도 보면서 몇가지 질문드립니다!

- WAS는 이미 public IP를 가지고 있는데 IGW는 왜 필요할까요?
- 라우팅 테이블은 왜 필요한가요? 라우팅 규칙은 어떻게 설정해주셨나요?
- private subnet에 별도로 NAT 구축은 필요없을까요?
- DB나 WAS 이중화에 대해서 들어보거나 학습해보셨나요? 만약 이중화 된다면 클라이언트 <-> WAS <-> DB 간의 네트워크 구조를 어떻게 할지에 대해 고민해보면 좋을 것 같습니다. 연습 단계에서 구성할 필요는 없지만 공부해보시면 좋은 주제일 것 같습니다!

이어서 리뷰 남기겠습니다! 코멘트에 답변 남겨주시고 merge하도록 하겠습니다! :)

2023-05-19 05:46 UTC, ninaaano commented
엇 수정중이였는데 벌써 보셨군요...!!!!!!!!!!!!!!!안돼....!!!!!!!

2023-05-19 06:39 UTC, seyoung755 commented on BE/README.md
> +github action에서 무료로 제공하는 CI툴입니다.
CI 도구로 Github Actions를 사용하기로 하신 것 같은데 업데이트가 안된걸까요?

2023-05-19 06:39 UTC, seyoung755 commented on BE/build.gradle
> +sourceCompatibility = '11'
버전 수정 및 패키지명 수정 좋네요 👍

2023-05-19 06:39 UTC, seyoung755 commented on BE/build.gradle
> + */
아마 RestDocs 관련 의존성을 처음 사용해보셔서 학습용으로 주석 남겨주신 것 좋은 것 같습니다!

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
> +    private String region;
이런 app key와 같은 값들을 property로 관리하는 것은 굉장히 좋습니다! 👍  몇가지 보완점을 소개드립니다.
- 보통 key는 여러개가 `cloud.aws` 등의 공통된 접두사를 가지고 관리되는 경우가 많은데요. 이 때 별도의 property 클래스를 만들고 `@ConfigurationProperties`로 관리하면 좀 더 깔끔하게 관리할 수 있습니다. 해당 어노테이션은 prefix를 지원하고, 필드명을 property와 똑같이 맞춰주면 알아서 camel case로 바인딩되어 좀 더 깔끔하게 관리가 가능합니다! 
- 현재 사용하신 방법에서는 `final` 키워드를 사용할 수 없어 이런 key 정보가 변경될 여지가 생기는데요. 그래서 저는 `@ConfigurationProperties`와  `@ConstructorBinding`을 조합한 생성자 바인딩 방식을 추천드립니다.

관련해서 학습 키워드도 전달드립니다.

- 해당 방식은 어떤 방식으로 property를 주입받고 있나요?
- Spring에서 제공하는 property 주입 방법은 어떤 것들이 있나요?

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
> +@RequiredArgsConstructor    // final 멤버변수가 있으면 생성자 항목에 포함시킴
기록해주신건 좋지만 간단한 어노테이션이라 주석은 없어도 되지 않을까요?

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
> +@Service
`@Component`와` @Service`를 같이 사용하셨네요.
결론부터 말씀드리면 `@Service `어노테이션 내부엔 `@Component` 어노테이션이 포함되어있어 `@Component`를 제거해도 괜찮습니다. 관련해서 질문 드릴게요!

- `@Component` 어노테이션은 왜 사용할까요?
- `@Component`와 `@Service `둘 다 빈으로 등록하기 위한 어노테이션들인데 그럼 두 어노테이션의 차이점은 무엇인가요?

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +    }
다른 곳에선 대부분 `@RequiredArgsConstructor`를 사용해서 생성자를 만드신 것 같은데요. 방식을 통일하는게 좋을 것 같네요!

추가로 생성자에 `@Autowired`를 붙이신 이유가 궁금합니다!
안붙이면 어떻게 되나요?

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +        return new ResponseEntity<>(createdIssue, HttpStatus.CREATED);
이슈를 만드는 경우 `201 CREATED` 로 응답하시는군요! 👍  클라이언트분들과 정한 방식인가요?

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
> +    public String upload(@RequestParam("image")MultipartFile multipartFile)throws IOException{
이부분 린트가 조금 어색하네요 !

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
> +@Data
`@Data `어노테이션을 사용해주신 이유가 있을까요? 그리고 `@Data` 어노테이션을 붙이면 어떤 기능들이 추가되나요?

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +@Setter // 주요 식별자 값의 자동 생성 기능을 제공하지 않기때문에 따로 처리 필요함
주요 식별자 값의 자동생성기능을 제공하지 않는게 어떤 의미인가요?

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    private String contents;
여기는 `@Column`을 적어주지 않아도 해당 이름으로 컬럼이 생성될 것 같네요! 명시적으로 적어주는걸 선호하신걸까요?

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/member/Member.java
> +public class Member {
전체적으로 도메인 객체에 생성자가 빠져있네요! 도메인 객체 생성시 초기화는 어떻게 하실건지 궁금합니다!

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
> +    }
Milestone이 Issue 객체의 `openStatus` 필드를 getter로 접근해 해당 이슈가 open인지 close인지 판별하고 있군요!
대신 Issue에서 판단해서 boolean을 반환하도록 하는 메서드를 이용하는건 어떨까요? 이런 흐름이 조금 더 객체지향적으로 보입니다!

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
> +    public String bucket;
필드가 public으로 열려있네요? 특별한 이유가 없다면 private으로 닫아주는게 좋을 것 같습니다.

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +    }
여기도 `IssueController` 쪽 코멘트 참고해주세요!

2023-05-19 06:39 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        return (List<Issue>) issueRepository.findAll();
바로 캐스팅하는 것보다는 stream을 이용해서 변환해주시는게 좋을 것 같아요! 또는 좋은 방법은 아니지만 IssueRepository쪽에 List<Issue>를 반환하도록 findAll을 override해주시면 편하게 사용할 수 있습니다!

2023-05-19 06:40 UTC, seyoung755 requested changes

2023-05-19 06:40 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +public class IssueService {
전반적으로 service layer에 `@Transcational` 이 빠져있는데요. 비즈니스 로직을 트랜잭션으로 관리하기 위해 추가가 필요해보입니다. 어노테이션과 트랜잭션 개념을 학습해보시고 적용해주세요!

2023-05-19 06:42 UTC, seyoung755 commented on BE/src/test/java/team05/codesquad/issuetracker/controller/IssueControllerTest.java
> +class IssueControllerTest {
테스트코드를 활용한 RestDocs 작성 좋습니다 👍 원래 Swagger를 사용하신다고 하셨던거 같은데 변경된거 같네요?ㅎㅎ

2023-05-19 06:42 UTC, ninaaano commented on BE/README.md
> +github action에서 무료로 제공하는 CI툴입니다.
넵... 원래 Travis로 yml 올렸다가... 삭제했습니다...

2023-05-19 06:44 UTC, seyoung755 commented on BE/src/main/resources/application.properties
> +spring.profiles.include=localDB
요거 관련 property는 추가될 예정인가요?ㅎㅎ

2023-05-19 11:42 UTC, ninaaano commented on BE/src/main/resources/application.properties
> +spring.profiles.include=localDB
개인정보가 들어있는 파일이라 숨겨놨습니다! 관련 property라는게 어떤...말씀이실까요...?

2023-05-19 11:42 UTC, ninaaano commented on BE/src/test/java/team05/codesquad/issuetracker/controller/IssueControllerTest.java
> +class IssueControllerTest {
뭉남이가 간지가 안난다고 REST docs 쓰자고 그래가지고....🤨

2023-05-19 11:44 UTC, KOKEONHO commented on BE/build.gradle
> + */
넵 ! 블로그에 나와있는 글 그대로 적긴 했지만 ... 적으면서도 공부 되고 계속 읽어보게 되더라구요

2023-05-19 11:44 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
> +@RequiredArgsConstructor    // final 멤버변수가 있으면 생성자 항목에 포함시킴
부끄럽지만.. 이 어노테이션을 처음써봐서... 학습한다고 적어놨던걸... 지우겠습니다

2023-05-19 11:46 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
> +@Service
* @Component 어노테이션은 스프링이 빈 컨테이너에 추가해야 할 것에 @Component 어노테이션을 다는 것 아닌가요 ...?
* 두 어노테이션의 차이점은 공부해보고 다시 답글 달아보겠습니다 !

2023-05-19 11:46 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +    }
안 붙여도 자동으로 @Autowired가 되는 것으로 알고 있지만, 뭔가 명시적으로 선언을 해 주는 것이 좋을 것 같다고 생각해서 @Autowired를 붙였습니다.

2023-05-19 11:48 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +        return new ResponseEntity<>(createdIssue, HttpStatus.CREATED);
아 저 부분은 REST Docs 공부하면서 찾아보니 POST 메서드로 엔티티(?)가 생성이 될 때 명시적으로 201로 응답하는 것이 바람직하다고 하여서 저렇게 코드를 작성했습니다. 클라이언트와 따로 협의는 되지 않아서 아직 확정은 아닐 것 같습니다 ... 아무래도 학습을 하면서 하다보니 뒤죽박죽인 것 같습니다 ㅠ 추가적으로 공부 더 해보고 확정짓겠습니다.

2023-05-19 11:49 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
> +@Data
@Data 어노테이션을 붙이면 Getter, Setter 등을 비롯한 기능과 toString을 했을 때 자동으로 작성해주는 것으로 알고 있는데, 정확하진 않지만 김영한님의 스프링 강의를 들을 때 @Data는 지양하는 것이 좋다고 말씀하셨던 것 같습니다.

2023-05-19 11:52 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    private String contents;
다른 조와 얘기를 나눠보니 카멜 케이스에서 스네이크 케이스로 자동으로 컨버팅을 해주는 기능이 있다고 하여 @Column 어노테이션을 뺄까 고민중이었습니다. 하지만 뭔가 명시적으로 적어주는 것이 좋지 않을까 하는 생각도 동시에 들어서 ... 니노와 상의하고 결정하겠습니다 !

2023-05-19 11:53 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
> +    public String upload(@RequestParam("image")MultipartFile multipartFile)throws IOException{
수정하겠습니다!

2023-05-19 11:54 UTC, KOKEONHO commented on BE/src/test/java/team05/codesquad/issuetracker/controller/IssueControllerTest.java
> +class IssueControllerTest {
제가 ... 갑자기 홍대병에 걸려 버리는 바람에 ...

2023-05-19 11:54 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +public class IssueService {
넵 학습하겠습니다 !

2023-05-19 11:55 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +@Setter // 주요 식별자 값의 자동 생성 기능을 제공하지 않기때문에 따로 처리 필요함
학습을 위해 강의를 수강했는데 강의에선 JPA 기준으로 설명을 했습니다. auto_incresement를 생성하주는 어노테이션이 있었는데 JDBC는 그런 어노테이션이 없었기 때문에 추가해주려고 적어놨습니다!

2023-05-19 11:56 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/member/Member.java
> +public class Member {
Getter,Setter를 간편하게 정의하려고 넣은건데 @Data 어노테이션의 정의를 제대로 알지 못하고 쓴 것 같습니다..ㅠㅠ

2023-05-19 11:56 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
> +    }
확인하고 수정하겠습니다!

2023-05-19 14:46 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        return (List<Issue>) issueRepository.findAll();
넵 ! stream 사용하여 반환하도록 수정하겠습니다 !

2023-05-20 01:48 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +    }
넵 이건 개발자들간에 컨벤션을 정하기 나름이라 명시적으로 적어주는게 편하시다면 그렇게 하셔도 좋아요 ㅎㅎ

2023-05-20 01:49 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +        return new ResponseEntity<>(createdIssue, HttpStatus.CREATED);
넵..! 클라이언트 단에서는 응답값을 기반으로 비즈니스 로직이 동작하거나 예외처리를 하기 때문에 협의가 필요한 부분일것 같네요! 물론 2xx 대의 성공 응답은 하나로 처리되는 방식을 사용할수도 있겠지만요 ㅎㅎ

2023-05-20 01:50 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
> +    public String upload(@RequestParam("image")MultipartFile multipartFile)throws IOException{
이미 아실수도 있지만 SonarLint 등의 인텔리제이 플러그인을 사용하면 커밋 시에 린트를 잡아주는 기능을 제공받을 수 있어요 ㅎㅎ

2023-05-20 01:52 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
> +@Data
넵 맞습니다. `@Data`를 추가하게 되면 Getter/Setter, ToString, EqualsAndHashCode , RequiredArgsConstructor 어노테이션이 한번에 적용되는데요. 보통 엔티티 객체에 Setter를 열어주는 것을 안티 패턴이라고 생각하기 때문에 보통은 지양하는 편이긴 합니다. 그래서 필요한 어노테이션만 달아서 사용하는 걸 추천드려요!

2023-05-20 02:02 UTC, seyoung755 commented on BE/src/main/resources/application.properties
> +spring.profiles.include=localDB
profile을 include 해주셨는데 application-localDB.properties 는 보이지 않는거 같아서 질문드렸어요 ㅎㅎㅎ

2023-05-20 13:27 UTC, ninaaano commented on BE/src/main/resources/application.properties
> +spring.profiles.include=localDB
.gitinore에 추가해서 숨겼습니닷. 디비 접속 정보가 들어있어서...

2023-05-20 13:27 UTC, ninaaano commented
산토리 피드백 반영해서 다시

2023-05-20 13:28 UTC, ninaaano commented
산토리 피드백 반영해서 다시 PR보냈습니다!

2023-05-20 14:01 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +        return new ResponseEntity<>(createdIssue, HttpStatus.CREATED);
아 그렇군요 ! 감사합니다 협의 해보고 다시 결정하겠습니다 !

2023-05-20 14:02 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
> +@Data
네 ! 이 부분 니노와 상의해서 @Data는 사용하지 않는걸로 결정했습니다

2023-05-20 14:03 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +    }
넵 !

2023-05-20 16:52 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
> +    private String region;
- @Value 키워드를 통해 yml에 있는 프로퍼티 값을 단일로 주입시키고 있습니다.
- @ConfigurationProperties를 사용하면 prefix = "prefix"를 통해 접두사(prefix)로 시작하는 프로퍼티들을 한 번에 관리할 수 있어 구성이 복잡한 경우 유용합니다. 시도해봤는데 에러를 잡을 수가 없어서 class만 분리해서 @Value키워드를 사용했습니다...ㅠㅠ

2023-05-20 16:57 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
> +@Service
- @Component 어노테이션은 스프링 프레임워크에서 컴포넌트 스캔을 통해 해당 클래스를 빈으로 등록하기 위해 사용됩니다.
- @Service는 비즈니스 로직을 담당하는 클래스임을 명확히 표현하기 위해 사용되며, @Component는 일반적인 컴포넌트 클래스임을 나타냅니다. 스프링은 두 어노테이션을 모두 컴포넌트 스캔 대상으로 삼아 빈으로 등록합니다. 일반적인 컴포넌트 클래스인 경우 @Component를 사용하고, 비즈니스 로직을 담당하는 클래스인 경우 @Service를 사용하는 것이 일반적이라고 합니다.
- 컴포넌트 클래스? 컴포넌트는 "구성 요소"를 말합니다. 컴포넌트 클래스는 일반적으로 특정 기능 또는 업무 영역을 담당하는 클래스를 의미합니다. 예를 들면 웹 애플리케이션에서 회원 관리, 상품 관리, 주문 처리 등을 담당하는 클래스들을 컴포넌트 클래스 라고 부를 수 있습니다.

2023-05-20 16:59 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
> +    }
`public Map<String, Long> countIssues() {
        long openIssueCount = Issue.countOpenIssues(issues);
        long closedIssueCount = Issue.countClosedIssues(issues);

        Map<String, Long> issueCounts = new HashMap<>();
        issueCounts.put("open", openIssueCount);
        issueCounts.put("closed", closedIssueCount);
        return issueCounts;
    }`
    마일스톤에선 이렇게 변경해주었습니다. 
    대신 issue class에서
`public static long countOpenIssues(List<Issue> issues) {
        return issues.stream()
                .filter(Issue::getOpenStatus)
                .count();
    }

    public static long countClosedIssues(List<Issue> issues) {
        return issues.stream()
                .filter(issue -> !issue.getOpenStatus())
                .count();
    }`
이 메소드를 추가한걸로 변경했습니다.

2023-05-20 17:01 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        return (List<Issue>) issueRepository.findAll();
```
public List<Issue> getAllIssues() {
        List<Issue> issueList = new ArrayList<>();
        issueRepository.findAll().forEach(issueList::add);
        return issueList;
    }
```

이렇게 수정해주었습니다. issueRepository.findAll().stream()을 바로 사용할 수가 없어서 이렇게 해주었습니다

2023-05-20 17:40 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/config/S3Uploader.java
> +    public String bucket;
수정헸ㅅ,ㅂㄴ다

2023-05-21 05:06 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
> +    private String region;
그렇군요 ㅠㅠ @Value 키워드를 작성하면 스프링이 어떻게 필드를 초기화하게 되는지 원리도 학습해보시면 좋을 것 같습니다!

2023-05-21 05:22 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
> +    }
아 저는 filter에 들어가는 부분만 수정하는걸 말씀드리려고 했는데 아예 기능을 분리하셨군요..! 👍

2023-05-21 05:27 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
> +    @Value("${region.static}")
음.. ConstructorBinding을 사용해주셨지만 이 클래스엔 현재 생성자가 없는데요 ㅠㅠ 이러면 ConstructorBinding을 통해 바인딩되는게 아니라 기존에 적어주신 @Value를 통해서 바인딩되고 있는 상황입니다.

@Value를 사용하게 되면 Spring이 해당 필드를 setter로 접근해서 초기화하게 됩니다. 관련해서 자료가 있는 블로그 링크를 첨부드리니 한번 읽어보시길 바래요 ㅎㅎ

https://tecoble.techcourse.co.kr/post/2020-09-29-spring-properties-binding/

2023-05-21 05:28 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
> +@AllArgsConstructor
Data 어노테이션을 사용하시는것은 상관없지만 꼭 모든 어노테이션이 필요할지 고민해서 달아주시는걸 부탁드려요!

2023-05-21 05:32 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
> +    @Value("${region.static}")
아 이후 커밋에 수정해주셨군요..! 예전커밋만 봤네요 ㅠㅠ 죄송합니다!

2023-05-21 05:34 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/auth/S3Properties.java
> +@Configuration
여기 `@Configuration`이 아니라 `@Component`만 붙여줘도 빈 등록이 가능한데요 `@Configuration`의 역할에 대해서 조사해보시면 좋을 것 같아요!

2023-05-21 05:36 UTC, seyoung755 commented
답변 확인했습니다! 이번주 PR은 머지하도록 하겠습니다! 추가적으로 학습해보시면 좋을 코멘트들 추가로 남겼습니다.

2023-05-21 05:36 UTC, merged

2023-05-21 13:53 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/comment/Comment.java
> +@AllArgsConstructor
감사합니다!

2023-05-21 14:14 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/auth/S3Properties.java
> +@Configuration
### @Component

스프링 컨텍스트에 의해 관리되는 컴포넌트 클래스를 선언하기 위해 사용된다.이 어노테이션은 해당 클래스가 자동으로 검색되어 스프링의 빈으로 등록되며, 스프링 컨텍스트에서 해당 빈을 사용할 수 있도록 해준다. 주로 일반적인 컴포넌트, 서비스, 레포지토리 등과 같은 역할을 하는 클래스에 사용한다

### @Configuration

스프링 빈 구성을 정의하는 클래스임을 나타내는데 사용된다. 이 어노테이션은 스프링 컨텍스트에게 해당 클래스가 빈 구성을 포함하고 있으며, 해당 클래스 내의 빈들을 생성하고 구성해야 한다는 것을 알려준다. 주로 빈 설정, 빈 생성 메서드, 빈 간의 의존성 등을 관리하는 클래스에 사용한다. @Bean 어노테이션을 사용하여 빈을 정의하고 반환하는 메서드를 가지게 된다. 이 메서드들은 스프링 컨텍스트에 의해 호출되어 해당 빈이 생성되고 구성되며, 다른 빈들과의 의존성을 주입 받을 수 있게 된다.

2023-05-21 14:15 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/S3TestController.java
> +    public String upload(@RequestParam("image")MultipartFile multipartFile)throws IOException{
몰...랐습니다.....부끄....

2023-05-21 14:17 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
> +    }
아...앗...제가 잘 몰라서......ㅠ

2023-05-21 14:19 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
> +    @Value("${region.static}")
좋은 정보 알려주셔서 감사합니다!