[team-03 FE] Week2 PR
codesquad-members-2023/issue-tracker pull request #41
Opened 2023-05-19 03:04 UTC by sjuhan123

안녕하세요 빰빰,

이번 주도 잘 부탁드립니다.
감사합니다!

# 📍 구현 진행 된 내용

https://github.com/codesquad-members-2023/issue-tracker/assets/81420856/2139ec34-51dc-43b2-bec7-6ae851b06029

# 📍 고민

### Button 컴포넌트

- 여러 페이지에서 공유할 Button 컴포넌트를 구현 중에 있습니다. 
현재는 Button 컴포넌트가 수많은 옵션들을 props로 받아서, Button 의 css 속성, Button 의  text, 숫자 등 을 설정할 수 있는 상황입니다. 여기에 추가로 사용자가 Button 컴포넌트 내에 다른 내용을 추가하고 싶을 때를 대비해서, children 옵션도 설정했습니다.
근데 사용자가 Button 컴포넌트를 사용할 때 props로 넘겨줄 수 많은 옵션들을 일일히 설정해야 되서, 사용성 및 범용성 측면에서 올바른 방향인지 고민이 됩니다.

### 드롭다운 컴포넌트

- 드롭다운 컴포넌트가 과연 재사용이 가능한 컴포넌트일까?
	- config에 css 관련 값들을 하드 코딩하는게 괜찮은 방법인지?

### 중앙 상태 관리

- 상태를 다음과 같이 고민중인데, 올바른 방향일까?
	- 페이지네이션을 아마도 구현할 것 같아서 전체적인 상태에 대한 고민을 다시 하게 됨.
	- 한 페이지에 해당하는 이슈 목록은 state로 관리
	- 페이지네이션을 하게 되면 전체 이슈가 오지 않게 되므로 열린 이슈, 닫힌 이슈의 개수는 state로 관리
	- 라벨과 마일스톤은 필터 드롭다운을 클릭하면 정보를 알고 있어야 하기 때문에 전체 라벨과 마일스톤을 가져온다. 따라서 전체 목록을 state로 관리
		- 라벨과 마일스톤의 개수는 dervied될 수 있으므로 state로 관리 X
		- 
	- useState(또는 useReducer)와 Context의 조합으로 App.jsx에 있는 상태들을 전역으로 분리하는게 적절할까?

2023-05-19 04:06 UTC, Jerome-Yoo commented
고생하셨습니다~ 질문만 먼저 다뤄볼게요.

2023-05-19 04:09 UTC, Jerome-Yoo commented
> Button 컴포넌트
> 현재 Button 컴포넌트를 개발 중이며, 이 컴포넌트는 여러 페이지에서 공유될 예정입니다. 현재 Button 컴포넌트는 많은 옵션들을 props로 받아서 Button의 CSS 속성, 텍스트, 숫자 등을 설정할 수 있게 설계되어 있습니다. 또한, 사용자가 필요에 따라 Button 컴포넌트 내에 추가적인 내용을 포함할 수 있도록 children 속성을 활용하고 있습니다.
- 커스터마이징의 자유도를 높게 한다는 말은 반대로 말하면 일일이 설정해줘야할 값이 늘어난다는 말과 동치이기도 합니다.

> 그러나, 사용자가 Button 컴포넌트를 사용할 때마다 모든 옵션들을 일일히 설정해야 하는 번거로움이 있어서 사용성과 범용성 측면에서 올바른 방향인지 고민 중입니다.
- 이런 경우 대부분 디폴트 값을 적절하게 주는 것을 통해 해결합니다. 
  - 모든 prop에 각각 기본값을 할당할 수도 있겠구요.
  - 자주 활용되는 값을 묶어서 쓰기도 합니다. 예를 들면
    - `button size="small" | "medium"` -> 크기를 기준으로 미리 잡힌 기본값을 활용
    - `button size="primary" | "warning"` -> 색상을 기준으로 미리 잡힌 기본값을 활용

2023-05-19 04:17 UTC, Jerome-Yoo commented
> 드롭다운 컴포넌트
> 드롭다운 컴포넌트가 과연 재사용이 가능한 컴포넌트일까?
- 재사용이 어렵다고 생각한 이유는 무엇인가요? 실제로 많은 라이브러리에서 드랍다운은 찾아볼 수 있는 컴포넌트예요 (쉽게말하면 재사용이 가능하다)
- https://www.radix-ui.com/docs/primitives/components/dropdown-menu
- https://ant.design/components/dropdown
- 말고도 많습니당.

> config에 css 관련 값들을 하드 코딩하는게 괜찮은 방법인지?
- 무슨말인지 몰라서 코드를 먼저 보고 왔습니다. 이렇게 짜여있더군요
```js
config: {
  buttonText, headerText, bodyItems, bodyCheck, posright, marginTop,
}
```
네이밍만 놓고 볼게요. 실제로 의미적으로 유저가 입력한 값에 의해 좌우된다고 생각하는 부분은 `buttonText, headerText` 인 것 같구요
`bodyItems, bodyCheck` 요거 두개는 사실 뭔지 잘 모르겠어서 저녁에 코드를 볼때쯤 볼 수 있을 것 같구요
`posright, marginTop` 이거 두개는 높은 확률로 스타일을 위한 값이겠군요.

앞서 스타일에 대한 디폴트 값을 주는것이 필요해보인다고 코멘트 드렸었구요. 스타일 값은 유저(컴포넌트를 사용하는 개발자)의 선택에 의해 오버라이딩할 수 있도록 만들면 좋습니다.

이런 의문도 있을 것 같아요. "너무 많은 값을 유저의 입력에 의존하게 하는 것 아닌가."
https://ant.design/components/modal
이건 앤트디자인이라고 하는 라이브러리의 모달이라고 하는 컴포넌트인데요. API부분을 보면 유저가 실제로 오버라이드할 수 있는 property가 나열되어 있어요. 30개를 직접 입력할 수 있게 하고 있군요. 원래 유저의 입력에 의존하는 값은 재사용가능하면 가능할수록 그렇습니다 허허

2023-05-19 04:20 UTC, Jerome-Yoo commented
> 중앙 상태 관리
> 한 페이지에 해당하는 이슈 목록은 state로 관리
> 페이지네이션을 하게 되면 전체 이슈가 오지 않게 되므로 열린 이슈, 닫힌 이슈의 개수는 state로 관리
- 좋은 생각입니다 다루는 상태에 기능적인 변화가 되어 derived하다고 판단했던 것이 그렇지 않게 되었군요.

> 라벨과 마일스톤은 필터 드롭다운을 클릭하면 정보를 알고 있어야 하기 때문에 전체 라벨과 마일스톤을 가져온다. 따라서 전체 목록을 state로 관리
> 라벨과 마일스톤의 개수는 dervied될 수 있으므로 state로 관리 X
- 좋은 판단입니다.

> useState(또는 useReducer)와 Context의 조합으로 App.jsx에 있는 상태들을 전역으로 분리하는게 적절할까?
- 적절하지 않을 것 같고 생각하는 이유를 작성해주시면 답변에 도움이 될 것 같습니다~ 그냥 놓고 보면 안될 이유는 없지요? 다만, 어떤 개발 방향이나 원칙이 있고 그에 부합하지 않는다면 고민해볼 수 있을 것 같은데, 그런 내용은 공유되어 있지 않은 것 같아요.

2023-05-20 18:14 UTC, Jerome-Yoo requested changes
고생하셨습니다 코멘트를 체크해보시구요, 코멘트 의사소통이 완료되었을 때 Approve를 진행하도록 하겠습니다.

이전PR과 다르게 컴포넌트의 폴더링이 시작하게 되어 좋다는 생각이 들었습니다.
불편함을 느끼셨으면 해서 따로 언급하지는 않았는데, 바로 다음주에 개선이 되어 좋다고 생각되었습니다 👍👍 

반대로 동일한 이름을 가지는 jsx가 만들어지게되어 import하는 시점에서도 두번이상 같은 이름이 노출되는 경우를 볼 수 있었습니다. 이런 부분은 해소되어야 하는 지점으로 받아들여지는데 어떻게 생각하시나요?

전체적으로 고민해볼 수 있는 부분을 보내드렸는데요 찬찬히 확인해보셔요!

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/assets/LogotypeMedium.svg
얘만 카멜케이스로 안다뤄지고 있군요?

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +`;
[적극]
이렇게 되면 버튼의 스타일이 드랍다운이라는 부모의 div에 종속되게 되는 군요.
심지어 드랍다운 하위의 모든 버튼의 태그가 이 속성에 영향을 받게 되니까, 버튼에게 직접 스타일을 부여하도록 합시다.

fyi. 버튼을 스타일드컴포넌트로 해도 괜찮고, css``로 만들고 주입해도 괜찮고, 인라인 스타일로 해도 괜찮습니다.

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +  const divEl = useRef();
[적극]
`divEl`은 ref에 직접 부여되고, 이것이 useEffect에서 이벤트 핸들링을 할 때 직접 활용되는데요, 드랍다운의 전체 영역을 잡고 있다는 명확한 네이밍을 사용하도록 합시다

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +        onClick={() => setIsOpen((prevIsOpen) => !prevIsOpen)}
[질문] 
토글하는 역할을 하는 함수군요. `setIsOpen((prevIsOpen) => !prevIsOpen)` 
set함수에 함수를 넘기는 이유가 무엇인가요? 

`setIsOpen(!isOpen)` 이렇게 작성하지 않은 이유는 무엇인가요?

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +    };
[적극]
클릭이 어떤 역할을 하는지 함수에 밝혀져 있지 않아서 어떤 의미인지 한번에 이해할 수 없습니다.
로직을 반드시 리딩해야지만 어떤 역할을 할 수 있는지 알 수 있는 함수라는 점에서 차후 레거시처럼 느껴질 수 있을 것 같아요.

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDownContent/DropDownContent.jsx
> +    <DropDownContentBox $posright={posright} margintop={marginTop}>
여기서는 `DropDownContentBox`의 prop에 달러사인이 붙어있네요? 오타겠죠?

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDownContent/DropDownContent.jsx
> +    <DropDownContentBox $posright={posright} margintop={marginTop}>
제가 오타인 줄 알고 다른 코드들도 봤다가 달러사인들 다시 보고 올라왔습니다. 어떤 원칙? 같은게 있나보네요?
문제는 원칙이 어떤 것인지 코드를 봤지만 잘 가늠이 안됩니다..

괜찮으시면 맥락을 설명해주시면 코멘트를 달아볼 수 있을 것 같아요~

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/CheckBox/CheckBox.jsx
> +      // onChange={({ target: { checked } }) => onChange(checked)}
여러군데서 활용된 것으로 보아 미완성된 컴포넌트라고 봐야겠죠?

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/public/index.html
> +    <meta name="description" content="원활한 협업을 위한 issue tracker" />
메타 태그를 수정하셨네요~ 나중에 이런 부분도 공부해보시면 좋을 것 같아서 링크를 답니다.
https://www.daleseo.com/html-meta-tags-for-seo/

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +        }
쿼리스트링이 let으로 잡혀있으니까 언제든지 수정가능한 값처럼 다뤄지는 것 같아서 찝찝한 것 같아요.
```
const queryString = (() => {
       if (issueState === ALL) {
          return '';
        } else if (issueState === OPENED) {
          return '?state=true';
        } else if (issueState === CLOSED) {
          return '?state=false';
})()
```
IIFE를 이럴 때 써볼 수 있습니다 :)

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +          },
[적극]
제가 잘못 이해한 건지 모르겠는데,
theme.id가 라이트라면, 다크테마? 를 불러올 것 같은 함수네요.
의도한 대로 작동하는 것이라면, 한번에 알기 어려운 로직이라 생각되어서 적극 태그를 달아보겠습니다.
그냥 실수라면 고쳐주세용

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/TableToolBar/IssueStatusButtons/IssueStatusButtons.jsx
[질문]
Open이슈 버튼과 Close이슈 버튼을 병합해서 다루고 있는 이유가 무엇인가요?

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/TableToolBar/IssueStatusButtons/IssueStatusButtons.jsx
> +  };
[적극]
`setFilterOptions` 함수를 직접 다루는게 이상해요.

HTML을 처음 배웠을 때 버튼을 생각해보면, 버튼은 단순히 이벤트만 발생하는 형태로 작성했던 기억이 있을거예요.
지금 버튼에 내려주고 있는 핸들러 함수는 어떤가요? 제가 보기에는 너무 많은 맥락을 알고있는 함수가 되었다고 생각해요.
1. setFilterOptions를 업데이트 하기 위해 이전 상태 맥락을 먼저 받아야 한다. `...prevState`
2. 상태값을 업데이트 하기 위해 무언가 판별한다. `isOpend ? ...`

[적극]
prevState, newState라는 이름은 너무 일반적이고 추상적이에요. 지양해보도록 합시다.
`state:` 라는 property에는 상태라는 것 이외에 어떠한 의미도 담겨있지 않은데 이미 다루고 있는 것 자체가 상태아닌가? 굳이 필요했을까? 도 싶군요.

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/TableToolBar/IssueStatusButtons/IssueStatusButtons.jsx
> +      </Button>
너무 많은 것을 고민하다보니 요상한 형태가 되어버렸군요 ㅠㅠ
[제안]
자주 쓰이는 스타일과 관련된 값은 웬만하면 디폴트로 잡아서 처리하도록 하는게 어떨까요?

[적극]
네이티브버튼의 사용성을 해치지 맙시다.
일반 버튼을 쓸 때는 `<button>열린이슈</button>`이렇게 썼는데, <Button />을 쓸 때는 <Button buttonText="열린이슈" />  요것은 좀 이상한 것 같아요.

[적극]
buttonStatus는 너무 추상적이에요. 내부코드를 까봐야 사용할 수 있는 프로퍼티는 없는 것과 마찬가지라고 생각해주세요. 소스코드를 읽고와도 어떤 역할인지 모르겠는데요, active, disabled, 이런 느낌으로 활용하려는 것이라면 그에 맞도록 바꿔주시는 것이 좋을 것 같아요.

[적극]
버튼에 count는 버튼의 역할이라 볼 수 없는 프로퍼티인데요, 클릭 이벤트를 핸들링한다는 책임과도 무방하기에 다른 방향으로 수정이 필요하다는 생각이 듭니다.

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/TableToolBar/TableFilterButtons/TableFilterButtons.jsx
> +import tempImg from '../../../../assets/userImageSmall.svg';
[제안]
userImageSmall를 사용하고 있음을 밝히는 것이 어떨까요?

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +            setFilterOptions={setFilterOptions}
[제안]
setFilterOptions를 직접 내려주지 말고 filterOptions를 적절하게 업데이트할 수 있는 핸들러 함수를 만들어서 내려주는 것이 어떨까요?

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDownContent/DropDownBody/DropDownBody.jsx
> +    img, text, onClick, checked,
[제안]
위에서 onClick이라는 이름으로 데이터를 내려받고 있어서 아래에서 사용할 때도 헷갈리는 지점이 발생하는 것 같아요.
이벤트가 실제로 컴포넌트에 직접 바인딩 되지 않는 경우에는 해당 네이밍을 적절하게 변경하여 사용해봅시다

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDownContent/DropDownBody/DropDownBody.jsx
> +          }
[질문]
onClick에 function이 아닌 것이 올 수도 있나요? undefined가 될 수도 있어서 이렇게 처리한 것인가요?

2023-05-20 18:14 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/IssueTable.jsx
> +  );
[제안]
`<NoticeBox>검색과 일치하는 결과가 없습니다.</NoticeBox>`은 issueItem이라 볼 수 없을 것 같은데, 아래의 List라는 컴포넌트에서 issues가 0일 때 처리를 하는 것은 어떨까요?

2023-05-20 18:15 UTC, Jerome-Yoo commented on fe/.eslintrc.js
각 옵션이 왜 off가 되었는지는 좀 궁금하군요!

2023-05-20 18:16 UTC, Jerome-Yoo commented on fe/src/constants.js
상수 관리를 시도하시는 군요 좋습니다. 👍 
코드의 여러지점에서 상수처럼 쓰여지는 부분이 있던데 같이 다뤄지면 좋겠군요

2023-05-20 18:17 UTC, Jerome-Yoo commented on fe/src/components/common/index.js
앞으로 공통 컴포넌트를 뽑아서 써야겠다 싶으면 common에서 바로 접근하기 위한 것이죠? 좋은 시도입니다.
반대로 불편함이나 고통스러운 부분도 잇으니 사용하면서 느껴보시지요!

2023-05-20 18:22 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +          },
아 다시 돌아와서 보니까 현재의 테마가 lightTheme라면 다크로 바꿔줘군요.
흐음.. `currentTheme` 정도로 네이밍 핸들링을 해볼 수 있을 것 같기도 합니다.

2023-05-20 18:24 UTC, Jerome-Yoo commented
두분 코드 포매팅 환경이 동일한가 궁금하네요. 코드만 놓고 봤을 때는 서로 다를 수도 있겠다는 생각이 들어서 여쭤봅니다.
lint설정이 있으니 두분 다 lint에 의존하고 계신가요?

2023-05-20 18:34 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +            setFilterOptions={setFilterOptions}
[안봐도 되는 도전과제]
코드를 전체적으로 읽고 왔을 때 filterOptions를 다루는 로직이나 내부 상태를 굳이 밝히지 않아도 된다는 생각이 들어서 적절하게 감춰서 쓸 수 있는 MVVM처럼 다뤄지면 깔끔할 것 같다는 생각이 들었습니다.
아마도? MVVM이 무엇인지는 아마 많이 공부하고 계실테니 유용하게 볼만한 아티클을 퍼와볼게요.

- https://paulallies.medium.com/clean-mvvm-with-react-and-react-hooks-ebc37b22542f
- 위에것이 어려우면 https://hini7.tistory.com/145
- 위에것이 어려우면 https://react.vlpt.us/basic/20-useReducer.html

2023-05-20 18:39 UTC, Jerome-Yoo commented on fe/src/App.jsx
> +            setFilterOptions={setFilterOptions}
아티클을 이해하기 위해서는 아마도 커스텀 훅 개념을 알아야 할 수도 있습니다.
https://react.vlpt.us/basic/21-custom-hook.html

2023-05-21 04:36 UTC, zlx454545 commented
> * 재사용이 어렵다고 생각한 이유는 무엇인가요? 실제로 많은 라이브러리에서 드랍다운은 찾아볼 수 있는 컴포넌트예요 (쉽게말하면 재사용이 가능하다)
> * https://www.radix-ui.com/docs/primitives/components/dropdown-menu
> * https://ant.design/components/dropdown
> * 말고도 많습니당.

아 이 부분은 제가 만든 드롭다운 컴포넌트가 과연 변경사항에 잘 대처할 수 있는 재사용 가능한 컴포넌트인가? 라는 고민을 적어놨었습니다. 크롱도 수업중에 재사용은 상당히 높은 레벨의 고민사항이라 아직 제가 판단하기 어렵긴 하지만, 어느정도 올바른 방향으로 시도를 한건지가 스스로 의문이 들어서 고민사항에 넣었습니다.

> > config에 css 관련 값들을 하드 코딩하는게 괜찮은 방법인지?
> 
> * 무슨말인지 몰라서 코드를 먼저 보고 왔습니다. 이렇게 짜여있더군요
> 
> ```js
> config: {
>   buttonText, headerText, bodyItems, bodyCheck, posright, marginTop,
> }
> ```
> 
> 네이밍만 놓고 볼게요. 실제로 의미적으로 유저가 입력한 값에 의해 좌우된다고 생각하는 부분은 `buttonText, headerText` 인 것 같구요 `bodyItems, bodyCheck` 요거 두개는 사실 뭔지 잘 모르겠어서 저녁에 코드를 볼때쯤 볼 수 있을 것 같구요 `posright, marginTop` 이거 두개는 높은 확률로 스타일을 위한 값이겠군요.
> 
> 앞서 스타일에 대한 디폴트 값을 주는것이 필요해보인다고 코멘트 드렸었구요. 스타일 값은 유저(컴포넌트를 사용하는 개발자)의 선택에 의해 오버라이딩할 수 있도록 만들면 좋습니다.
> 
> 이런 의문도 있을 것 같아요. "너무 많은 값을 유저의 입력에 의존하게 하는 것 아닌가." https://ant.design/components/modal 이건 앤트디자인이라고 하는 라이브러리의 모달이라고 하는 컴포넌트인데요. API부분을 보면 유저가 실제로 오버라이드할 수 있는 property가 나열되어 있어요. 30개를 직접 입력할 수 있게 하고 있군요. 원래 유저의 입력에 의존하는 값은 재사용가능하면 가능할수록 많아집니다 하하 라이브러리 내부를 까보면(지금은 학습단계인지라 다른 프로덕션을 까보거나 그러지 않았으면 좋겠습니다) 실제로는 30개가 아니라 같은 property에 서로 완전히 다른 내용을 넣을 수도 있어서 체감상으로는 훨씬 더 많은 종류를 다루고 있다는 느낌을 받을 수도 있습니다.

네 정확히 이 부분을 조금 고민했었습니다. 이렇게 많은 값을 유저의 입력에 의존할거면 새로 컴포넌트를 만드는거랑 그다지 리소스 차이가 나지 않을 것 같다고 생각했는데 antd가 이렇게 했다면 분명히 이점이 있을것 같습니다. 이유에 대해 더 고민해보겠습니다!

> 미리 코멘트를 드리면,
> 
> * config로 맥락을 뭉개놓는 것이 좋다고 생각이 들지 않습니다. config에 무슨 값이 들어가야하는지 모르기 때문에 모든 config로부터 파생된 프롭들이 undefined로 떨어질 위험이 있다고 생각됩니다. 사용시점에 (런타임에) 에러를 내기 딱 좋은 상황같군요.

사실 명시하지 않을 경우 default 값을 주는 식으로 컴포넌트를 구성하려했습니다.
그래서 밑에 펑션 타입을 체크하는 코드도 같은 맥락입니다.
굳이 config로 한 객체로 합쳐서 옵션을 줬던 이유는.. 각 옵션들을 props로 바로 전달해주기는 좀 헤비한 로직이 들어갈 수도 있어서 였습니다. 예를 들어보면..

```
const 드롭다운1의옵션1 = 로직
const 드롭다운1의옵션2 = 로직
..

const 드롭다운3의옵션6 = 로직
```

이처럼 상위 컴포넌트에서 여러 개의 드롭다운을 자식 컴포넌트로 가질때 코드가 너무 지저분해지진 않을까? 하는 생각에 명시적으로 하나의 객체에 넣는게 더 적합하다고 생각했습니다. 따로 명시되지 않은 부분은 디폴트값이나 타입 체크를 통해 런타임 오류를 내지 않도록 해보자. 라고 생각했던것 같습니다. 사실 맥락을 해치지 않아야 한다는 부분이 확 와닿지 않아서, 학습 키워드를 부탁드려도 될까요?

2023-05-21 04:43 UTC, zlx454545 commented on fe/src/components/DropDown/DropDown.jsx
> +        onClick={() => setIsOpen((prevIsOpen) => !prevIsOpen)}
리액트의 상태 업데이트가 배칭 작업으로 인해 매번 동기적으로 작동하지 않다보니 이전 상태값에 의존하여 상태를 새롭게 업데이트 할 때는 함수형 업데이트를 사용해야 한다고 배워서 위와 같은 식으로 작성하였습니다. 혹시 큰 문제가 없다면 `setIsOpen(!isOpen)` 이렇게 작성하는게 가독성 측면에서 더 유리할까요?

2023-05-21 04:48 UTC, zlx454545 commented on fe/src/components/DropDown/DropDownContent/DropDownBody/DropDownBody.jsx
> +          }
넵 맞습니다. 위에서 말씀드린 것처럼 config에 굳이 null값을 일일히 적지 않도록 undefined로 올 경우 이런식으로 처리하려고 했습니다.

2023-05-21 04:50 UTC, zlx454545 commented on fe/src/components/DropDown/DropDownContent/DropDownContent.jsx
> +    <DropDownContentBox $posright={posright} margintop={marginTop}>
스타일드 컴포넌트의 이슈인것 같은데, 사실 깊게 파헤쳐보지는 못한 부분입니다 ㅎㅎ;
기본 html 태그에 (커스텀 어트리뷰트? 표준 어트리뷰트 말고 저희가 지정한 어트리뷰트에) boolean값을 프롭으로 주면 경고가 뜨더라구요. 그래서 다른 팀에 물어보니 $기호를 앞에 붙이면 해결된다 해서 일단은 이렇게 해놨습니다.

마찬가지로 margintop같은 경우도 카멜 케이스를 쓰면 경고를 줘서 일단 경고 지우자는 생각으로 수정하였습니다.

2023-05-21 05:38 UTC, zlx454545 commented
> > useState(또는 useReducer)와 Context의 조합으로 App.jsx에 있는 상태들을 전역으로 분리하는게 적절할까?
> 
> * 적절하지 않을 것 같고 생각하는 이유를 작성해주시면 답변에 도움이 될 것 같습니다~ 그냥 놓고 보면 안될 이유는 없지요? 다만, 어떤 개발 방향이나 원칙이 있고 그에 부합하지 않는다면 고민해볼 수 있을 것 같은데, 그런 내용은 공유되어 있지 않은 것 같아요.

이론적 깊이가 부족해 생기게 된 질문인데요 두가지 측면에서 고민했습니다.

1) Context를 이용해서 props drilling을 해결하고자 했는데,  불편하다는 것은 개인차가 있는 건데 어떤 기준으로 Context를 사용해야 할지? 에 대한 감이 잡히지 않았습니다. (현업에서는 몇단계 이상일때 Context로 빼는지 등도 궁금합니다.)
2) Context의 경우 리렌더링에 대해 최적화가 이루어지지 않는다고 알고 있습니다. 그럼 성능에 대한 명확한 지표는 또 어떤 걸 기준으로 삼아야 할지?에 대한 기준을 잡지 못했습니다.

(물론 저희가 보지 못한 점이 있겠지만) 결론적으로 개발의 용이함과 성능상의 트레이드 오프가 저희가 고려중인 부분인데 둘다 어떤 기준을 삼아야할까?에 대한 고민이었습니다.

// 앞으로는 좀 더 맥락을 담아 질문하겠습니다 ^^;

2023-05-21 05:44 UTC, zlx454545 commented on fe/src/components/IssueTable/TableToolBar/TableFilterButtons/TableFilterButtons.jsx
> +import tempImg from '../../../../assets/userImageSmall.svg';
데모때문에 급하게 넣느라.. 😂 
실제로는 서버에서 받아올 이미지입니답..

2023-05-21 05:52 UTC, zlx454545 commented
> 두분 코드 포매팅 환경이 동일한가 궁금하네요. 코드만 놓고 봤을 때는 서로 다를 수도 있겠다는 생각이 들어서 여쭤봅니다. lint설정이 있으니 두분 다 lint에 의존하고 있다고 봐야할까요?

넵 둘다 똑같은 설정입니다. 다음주에 한번더 확인해보겠습니다!

2023-05-21 05:59 UTC, zlx454545 commented on fe/src/components/DropDown/DropDown.jsx
> +`;
조금 다른 질문인데요, 정말 제 개인적인 느낌으로는 한 컴포넌트에서 (대부분의 경우 한 파일에서) styled를 사용하는 경우를 최소화 하는게 css 구조가 잘 보이는것같아서 최대한 네스팅을 많이해서 하나의 styled에 많이 담고자 했는데 이는 지양되어야 할까요?

2023-05-21 06:34 UTC, sjuhan123 commented on fe/src/components/IssueTable/CheckBox/CheckBox.jsx
> +      // onChange={({ target: { checked } }) => onChange(checked)}
네 맞습니다! 추가 구현 예정인 컴포넌트입니다.

2023-05-21 09:52 UTC, Jerome-Yoo commented
> 그래서 밑에 펑션 타입을 체크하는 코드도 같은 맥락입니다.
- 좋습니다. 방어로직은 그런 의미에서 들어갔다는 것이군요. 디폴트 값이 아직 할당되지 않아서 제가 맥락을 파악하기 어려웠던 것 같아요. 차후 기본값이 들어가면, 파악해볼 수 있을 것 같아요.

> 굳이 config로 한 객체로 합쳐서 옵션을 줬던 이유는.. 각 옵션들을 props로 바로 전달해주기는 좀 헤비한 로직이 들어갈 수도 있고 한 컴포넌트에서 드롭다운을 여러개 사용할수 있기때문이었습니다. 예를 들어보면..
> 
> const 드롭다운1의옵션1 = 로직
> const 드롭다운1의옵션2 = 로직
> ..
> 
> const 드롭다운3의옵션6 = 로직
> 이처럼 상위 컴포넌트에서 여러 개의 드롭다운을 자식 컴포넌트로 가질때 코드가 너무 지저분해지진 않을까? 하는 생각에 하나의 객체에 넣는게 더 적합하다고 생각했습니다. 따로 명시되지 않은 부분은 디폴트값이나 타입 체크를 통해 런타임 오류를 내지 않도록 해보자. 라고 생각했던것 같습니다. 사실 맥락을 해치지 않아야 한다는 부분이 확 와닿지 않아서, 학습 키워드를 부탁드려도 될까요?

- 상위 컴포넌트에서 여러 개의 드롭다운을 자식 컴포넌트로 가질때 코드가 너무 지저분해지진 않을까? 하는 생각에 하나의 객체에 넣는게 더 적합하다고 생각했습니다. 따로 명시되지 않은 부분은 디폴트값이나 타입 체크를 통해 런타임 오류를 내지 않도록 해보자. 라고 생각했던것 같습니다. 
  - 동의합니다. 객체로 묶게되면 실제 사용하는 시점에서는 객체를 넘기고, 선언하는 곳에서 필요한 것만 뽑아서 쓸 수 있다는 이야기를 해볼 수 있겠죠
  - 다만, 뭔가 객체로 묶이게되면, 실제로 사용하는 시점에는 해당 객체의 모든 프로퍼티를 알아야 확신을 갖고 쓸 수 있어요. 만약 객체에서 다루는 것이 10개가 넘어간다면, 분리를 시도해볼 수 있겠지만, 그 객체마저 종류가 10개가 넘어간다면, 10*10의 단순 경우의 수를 다뤄야겠군요.
  - 이런 문제를 나이스하게 해결할 수 있는 방법이 타입스크립트를 활용하는 방식인데, 차후 타입스크립트를 도입하는 시점에 무슨말인지 알 수 있을 것이라 생각합니다. 다만 우리는 지금 타입스크립트를 쓰지 않기 때문에, 각 객체에 어떤 값이 들어가는지를 매번 트래킹할 방법을 정의할 필요가 있겠습니다.
  - 지금은 그 양이 적은 상황이라 개발에 괜찮을텐데요, 분명 객체가 커지는 시점에는 모든 런타임에러를 적절하게 대처하기 어려울 수 있어요.
  - 이런 상황에서는 주석에 대부분 많이들 의존합니다. 아래의 jsdoc이 타입스크립트가 쓰이지 않는 시점에 특정한 영역의 주석을 문서로써 다룰 수 있는 좋은 방법이에요.
  - https://poiemaweb.com/jsdoc-type-hint

2023-05-21 09:58 UTC, Jerome-Yoo commented
이론적 깊이가 부족해 생기게 된 질문인데요 두가지 측면에서 고민했습니다.

> Context를 이용해서 props drilling을 해결하고자 했는데, 불편하다는 것은 개인차가 있는 건데 어떤 기준으로 Context를 사용해야 할지? 에 대한 감이 잡히지 않았습니다. (현업에서는 몇단계 이상일때 Context로 빼는지 등도 궁금합니다.)
- 현업도 뭐 크게 다르거나 그러지는 않습니다. 저희는 직관적으로 불편하면 위에서 프로바이딩 되도록 하자는 기준을 갖고 있구요. 경험상으로는 2depth부터 prop으로 내려주지 않도록 하고 있다고 할 수 있을 것 같아요.

> Context의 경우 리렌더링에 대해 최적화가 이루어지지 않는다고 알고 있습니다. 그럼 성능에 대한 명확한 지표는 또 어떤 걸 기준으로 삼아야 할지?에 대한 기준을 잡지 못했습니다. (물론 저희가 보지 못한 점이 있겠지만) 결론적으로 개발의 용이함과 성능상의 트레이드 오프가 저희가 고려중인 부분인데 둘다 어떤 기준을 삼아야할까?에 대한 고민이었습니다.
- 렌더링 최적화는 지금 이야기하기에는 너무 거대한 주제가 아닌가 싶습니다. 최적화라는 주제로도 책으로도 한권 나올 정도라서요.
- 다만, 실제로 현 시점에서 리렌더링이 문제인가? 를 고민해보면 좋겠군요. 그래서 리렌더링을 한두번 줄이는 것이 우리의 리소스를 큰 차원에서 쓸 정도로 낭비가 아닌 가치 있는 일인가? 혹은 FE애플리케이션을 개발하는 입장에서 불필요한 렌더링을 줄이는 것은 숙명같은 일이기 때문에 양보할 수 없는 일인가?
  - 이 부분은 두분의 답변을 들어보면 좋을 것 같다는 생각이 듭니다.

2023-05-21 10:00 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDownContent/DropDownBody/DropDownBody.jsx
> +          }
그렇다면 function에 대해 화이트리스트처럼 다루기 보다 undefined를 블랙리스트로서 아무 작업도 하지 않도록 처리하는 것이 더 필요해 보인다는 생각이 듭니다.
사실 제입장에서는 onClick은 이름에서 볼 수 있듯 함수로 너무나도 당연하게 추론이 되는데, 이게 함수인 경우만을 검사한다는게 이상해보여요.

2023-05-21 10:01 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/CheckBox/CheckBox.jsx
> +      // onChange={({ target: { checked } }) => onChange(checked)}
그렇다면 다음에는 주석을 부탁드립니다 🙏

2023-05-21 10:05 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDownContent/DropDownContent.jsx
> +    <DropDownContentBox $posright={posright} margintop={marginTop}>
하나 배웠습니다. 스타일드컴포넌트의 신규 기능이군요.
https://styled-components.com/docs/api#transient-props

2023-05-21 10:21 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +`;
오 지양되어야 하는 것은 아니구요. 만약 DropdownBox가 아니라 좀 더 의미있는 네이밍이었다면, button뒤에 특정 className이 붙어있었다면 그럴 수 있겠다는 생각을 할 수도 있을 것 같아요.
button이 어떤 역할을 하는지 모르는 상황에서 모든 버튼태그의 스타일을 오버라이드할 수 있는 코드가 있어서 태그를 달았던 것이에요.

제가 이 코드를 받고나서 들었던 생각의 흐름은 다음과 같아요.
1. 드랍다운 박스가 뭐지?
2. 정확히 드랍다운 박스가 무슨 역할을 하는거지?
  - 드랍다운의 영역을 정의하는 root 그이상의 역할을 하지 않는구나
3. button 스타일을 왜 오버라이드 하고 있지?
4. 이것은 버튼을 다루는 스타일컴포넌트의 역할 이라고 봐야하지 않나?
  - 리뷰 작성

2023-05-21 10:23 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +        onClick={() => setIsOpen((prevIsOpen) => !prevIsOpen)}
- 이 아티클이 이해에 도움을 줄 수 있을 것 같은데요
 - https://velog.io/@suyeonme/react-useState%EC%9D%98-%EB%B9%84%EB%8F%99%EA%B8%B0%EC%A0%81-%EC%86%8D%EC%84%B1-%ED%95%A8%EC%88%98%ED%98%95-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8#%ED%95%A8%EC%88%98%ED%98%95-%EC%97%85%EB%8D%B0%EC%9D%B4%ED%8A%B8

이야기하셨던 대로 비동기적인 상태 처리를 하고 있는 상황인지 궁금하군요?

2023-05-21 10:24 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDownContent/DropDownContent.jsx
> +    <DropDownContentBox $posright={posright} margintop={marginTop}>
그냥 문서를 읽었을 때는 boolean에 대한 이야기가 아닌데 싶어서 실제 어떤 에러가 발생하는지 궁금해서 소스코드를 내려받았는데요, 달러사인을 지워도 어떠한 오류도 발생하지 않는군요 ㅠㅠ
<img width="800" alt="image" src="https://github.com/codesquad-members-2023/issue-tracker/assets/88368753/938dc9c8-502e-4c69-bd7b-61ad0a3dd11d">
에러 로그를 보내주시면 같이 고민해볼 수 있는 주제인 것 같아요

2023-05-21 10:25 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDownContent/DropDownContent.jsx
> +    <DropDownContentBox $posright={posright} margintop={marginTop}>
fyi 파란색 줄은 오타같아 보이는 것에 체크를 해주는 익스텐션이라 신경쓰지 않으셔도 됩니다

2023-05-21 10:26 UTC, Jerome-Yoo commented
@sjuhan123 @zlx454545 커밋을 새로 올린다음 새로고침 비스무리한 버튼을 눌러주세요~
<img width="350" alt="image" src="https://github.com/codesquad-members-2023/issue-tracker/assets/88368753/7933dce0-21d6-4e1c-8133-91b134539fe9">

2023-05-21 10:34 UTC, Jerome-Yoo commented
끙.. 제가 다른 FE팀의 리뷰어분들 코멘트를 보고 왔는데요. 제가 여러분을 너무 쥐고 흔들고 있다는 반성을 하고 왔습니다.
다음번에는 코멘트의 양을 일단 지금의 절반정도로 줄여봐야겠다는 생각을 하고 왔어요.

괜찮으시면 이번주 리뷰방향과 관련된 내용으로 슬랙 허들을 해볼 수 있을까요?

2023-05-21 11:37 UTC, sjuhan123 commented on fe/src/components/IssueTable/TableToolBar/IssueStatusButtons/IssueStatusButtons.jsx
Issue Table의 상단 영역에서 왼쪽 영역(Open 이슈 버튼 + Close 이슈 버튼)과 오른쪽 영역(클릭시 모달이 뜨는 영역)이 각각 다른 기능과 역할을 한다고 생각해, 나누고, 각각의 영역에 있는 버튼들을 병합해서 다루게 됐습니다.

2023-05-21 12:25 UTC, zlx454545 commented on fe/src/components/DropDown/DropDownContent/DropDownContent.jsx
> +    <DropDownContentBox $posright={posright} margintop={marginTop}>
![image](https://github.com/codesquad-members-2023/issue-tracker/assets/76683390/21db544c-e35d-4887-8c74-ec1e03bd3dec)

이런식으로 콘솔창에서 에러가 나옵니다!

2023-05-22 01:18 UTC, Jerome-Yoo approved these changes

2023-05-22 01:47 UTC, merged