[BE][TEAM-05 : 고뭉남, 니노] 3주차 PR
codesquad-members-2023/issue-tracker pull request #47
Opened 2023-05-26 01:29 UTC by ninaaano

안녕하세요 산토리! 한 주간도 잘 보내셨나요?
지금 학원은 질병이슈가 생겼습니다.. 제 옆자리 동료가 코로롱에 걸려버렸지 뭐에요
건강 조심하세요🥺

--------------

2023-05-27 03:40 UTC, seyoung755 commented
3주차도 수고 많으셨습니다! 코로나가 아직도 유행이군요 ㅠㅠ 두분도 코로나 조심하시고 건강하시길 바래요!!
질문 남겨주신것 먼저 답변 드릴게요!!

> 이번주간은 DTO에 대해 고민을 많이 한 것 같습니다. SQL이나 전체적인 흐름 로직짜기도 잘 몰라서 공부를 해야할 것 같은데 논리력이 부족해서 그런지 메소드 하나 짤 때마다 시간이 너무 오래 걸립니다.. 프로젝트 잘 끝낼 수 있을지 걱정이 드네요

이런 고민은 프로젝트 하면 항상 드는 것 같아요..! 저는 이럴 때 예제 코드 같은걸 찾아보면서 일단 짜보는 방식으로 생각을 풀어나가곤 하는데요. 너무 고민이 많이 될 때는 일단 만들어보고 테스트 해보면서 보완해보는 것도 좋을 것 같습니다!

> 기존에는 feat 브랜치에서 작업하던 사항들을 dev-be로 푸시하거나 직접 옮겨 적는 방법을 사용했는데, 이번에 milestone-api 작업을 한 뒤 머지 충돌 해결 연습을 위해 dev-be로 머지시켜봤습니다. 많은 부분이 바뀌어서 자동 머지가 되지 않았고, 웹 에디터로 수정할 수 없을 정도로 복잡한 코드 충돌이라는 문구가 떠서 인텔리제이의 도움을 받아 머지 충돌을 해결했습니다. 제가 공부한 바로는 이렇게 머지를 시키게 되면 기존의 커밋 내역들이 따라오게 되는 것으로 알고 있는데, 혹시 이런 식의 브랜치 전략(?)이 문제를 일으킬 수도 있을까요 ?

우선 가장 좋은 방법은 feat 브랜치에서 작업하신 내용을 dev-be로 PR을 올려서 merge하시는 방법일 것 같네요..! 직접 push하거나 옮겨 적게 되면 ... 시간이 오래 지나거나 했을 때 어떤 배경에서 작업이 되었는지를 추적하기가 조금 어려울 것 같아서요. 좋은 브랜치 전략은 아닌거 같네요 ㅠㅠ 

아마 두 분이 같은 부분을 작업하거나 작업량이 많아지면 머지하는 과정에서 자연스럽게 충돌이 발생할 수 있는데요. 충돌을 해결해보는 연습을 해보시려는건 되게 좋은 것 같네요! 

그리고 그냥 머지를 하게 되면 자연스럽게 그 브랜치의 커밋 내역이 따라붙는건 자연스러운데요. 문제가 발생할 일은 없지만 조금 지저분해 보이는 건 있어서 저는 squash merge를 선호하는 편이긴 합니다! merge 종류 관련해서는 한번 찾아보시면 좋을 것 같아요!

> Rest Docs를 사용할 때 API 명세서 생성을 위해 테스트가 선행되어야 하는데, 직접 맞닥뜨린 문제점은 아니지만 나중에 단위 테스트를 진행할 때 혼란을 야기할 것 같다는 생각이 들었습니다. 혹시 패키지를 따로 나눠서 테스트를 설계하면 될까요 ? 예를 들어서 Rest Docs 생성 용 테스트 패키지와 실제 로직 테스트용 패키지를 분리하는 방법으로 분리하면 괜찮을까요 …?

좋은 고민이네요! 아무래도 RestDocs를 작성하기만을 위한 테스트가 생길수도 있고, 뭔가 단위 테스트와는 조금 다른 성격으로 느껴져서 저도 분리하는걸 선호하는 편입니다. 따로 RestDocs 작성용 테스트를 모아서 패키지화해놓으면 깔끔할 것 같습니다 👍 

이후 코멘트 남겨드릴게요!! 천천히 답변 주시고 오늘 밤이나 내일 중으로 머지할게요 👍

2023-05-27 03:40 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/auth/S3Properties.java
> +    }
오 해결하셨군요 !! 깔끔하네요 ㅎㅎㅎ 👍

2023-05-27 05:02 UTC, seyoung755 requested changes

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
> +@EnableConfigurationProperties(value = {S3Properties.class})
[코멘트] `S3Properties`를 빈으로 등록하기 위해 사용해주셨군요! 👍 
[의견] Spring boot 2.2 이후부터는 이걸 자동으로 등록해주는 기능이 생겼는데요! 참고해보시면 좋을 것 같습니다.
참고 링크: https://mangkyu.tistory.com/191

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +        return IssueResponse.from(issueService.findById(issueId));
[코멘트] 기존에 엔티티를 반환하시던걸 DTO로 바꿔주셨군요! 좋습니다 👍

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
> +        return ResponseEntity.ok().body(labelList);
[질문] LabelController에서만 컨트롤러 응답시 ResponseEntity로 wrapping이 되어있는 이유가 있나요?

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
> +        Iterable<Label> labelList = labelService.findAll();
[의견] Iterable이 다루기 귀찮다보니 그냥 List를 선호하는 편인데요.. 그래서 편하게 Repository에 findAll()을 List 반환하는 형태로 재정의해서 쓰셔도 좋을 것 같아요

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
> +    @PatchMapping("/{id}")
[참고] 보통 수정하는 HTTP 요청에는 PUT이나 PATCH등을 사용하는데요. 어떤 차이가 있는지 학습해보시면 좋을 것 같아요!

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/labeldto/LabelRequest.java
> +                .build();
[코멘트] 엔티티로 변환해주는 메소드 좋네요 👍 빌더패턴을 적용하신것도 좋습니다.
[참고] 근데 엔티티에 빌더 패턴을 사용하면 엔티티에 필드가 추가되는 경우에 이 메소드처럼 빌더 패턴이 사용된 곳에 추가를 깜빡하면 해당 필드는 null인 채로 엔티티가 만들어지게 될텐데요.
그럼 런타임에 오류를 일으키거나 최악의 경우에는 알아차리지 못하고 디버깅하기 어려운 문제가 생길 수 있습니다. 
최소한 엔티티에 null이면 안되는 필드에 null값이 들어올 때 보완할 수 있는 방법이 있을지도 고민해보시면 좋을 것 같아요.

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +        return issueService.findByOpenIssue();
[필수] 여기도 아래처럼 엔티티를 바로 리턴하기보다는 Dto로 변환시켜주시는게 좋을 것 같네요!

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/MilestoneController.java
> +    }
[제안] 여기는 생성자를 직접 만들어주셨고 `@RequiredArgsConstructor`를 붙여주신 부분도 있어서 컨벤션을 맞추면 좋을 것 같습니다!

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/MilestoneController.java
> +    @ResponseStatus(HttpStatus.OK)
[질문] 아마 기본적으로 200 응답이 내려갈 것으로 보이는데요! 특별히 이걸 붙여주신 이유가 있나요?

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueRequest.java
> +import java.time.LocalDateTime;
[코멘트] 불필요한 import가 보이네용 ㅎㅎ 정리하는 습관을 들여두시거나 IDE의 도움을 받으시면 좋습니다 👍

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueResponse.java
> +    //private List<Member> assignees;
[의견] 코드 내 불필요한 주석은 지워주시는 게 좋아용!

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/MilestoneDto.java
> +    }
[코멘트] 좋은 방법이네요 ㅎㅎㅎ 저는 정적 팩토리 메서드 용으로 `@AllArgsConstructor(access = AccessLevel.PRIVATE)`를 주로 사용합니다.

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/milestonedto/request/MilestoneUpdateRequest.java
> +@Slf4j @Getter
[코멘트]
가독성을 위해 어노테이션은 한 줄에 하나씩 쓰는게 좋아보입니다 ㅎㅎ

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    @Column("isOpened")
[필수] 보통 DB 컬럼 이름은 snake case를 사용하는 편입니다! 몇 군데 어긋난 곳이 있어서 다른 엔티티도 다같이 한번 맞춰주시면 좋을 것 같아요.

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    private List<Label> labels = new ArrayList<>();
[질문] Transient로 Labels를 들고 계시군요! 어떤 이유에서 이렇게 관리하게 되셨나요?

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    private AggregateReference<Milestone, @NotNull Long> milestoneId;
[질문] 현재 aggregate root를 Issue, Label, Milestone 이 3개로 설계를 가져가신건가요?

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/label/Label.java
> +    @NotBlank
[질문] `@NotBlank`의 용도에 대해서 학습해보셨나요?

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
> +    }
[질문] 생성자가 많아지게 된 배경이 궁금합니다!! `@AllArgsConstructor`까지 사용되고 있네요?!

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/milestone/Milestone.java
> +    }
[의견] MilestoneCreateRequest 내부에서 Milestone을 생성하는게 낫지 않을까요? (toEntity 등으로)
MilestoneCreateRequest 객체가 변하면 엔티티 객체의 코드가 수정되어야 하는게 바람직하진 않아보이네요!

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
> +    @Query("SELECT * from Issue where status = :isOpened")
[질문] 
Query를 따로 안적어줘도 기본적으로 findBy 메서드를 지원하지 않나요??

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        Issue issue = issueRepository.findById(issueId).orElseThrow();
[필수]
`orElseThrow()`들에 아무 동작도 담겨있지 않은데요. 적절한 예외를 던져주시면 좋을 것 같아요.

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueResponse.java
> +    private List<Label> labels;
[의견] 이렇게 되면 Label 객체가 그대로 json형태로 넘어가게 될 것 같네요. 여기도 dto 사용해주는게 좋을 것 같습니다!

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        return responseList;
[코멘트] 코드가 대부분 겹치네요..! 중복을 줄일 수 있지 않을까요?

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
> +@Transactional
[참고] `@Transactional`의 속성 중 readOnly에 대해서도 학습해보세요~

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
> +        Label targetLabel = labelRepository.findById(id).orElseThrow(() -> new NotFoundException(HttpStatus.NOT_FOUND + "정보를 찾을 수 없습니다"));
[질문] `NotFoundException`이 발생하면 클라이언트쪽에 응답은 어떻게 나가나요? 
[참고] 추가로 이 경우에 `NotFoundException`이 사용되는게 적절할까요? 
이 예외의 패키지가 com.amazonaws.services.kms.model.NotFoundException 인걸로 보아 aws 관련 라이브러리에서 사용되는 예외로 보이는데요. 적절한 예외를 찾아서 사용해주시거나 생성하는 걸 추천드려요! 예외처리나 설계 관련해서도 학습해주시는걸 추천드립니다.

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
> +        targetLabel.editLabel(request.getTitle(), request.getDescription(), request.getBackgroundColor(), request.getFontColor());
[필수] Label을 수정하고 update 문이 날아가는 코드가 빠져있는 것 같네요?

2023-05-27 05:02 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/MilestoneService.java
> +    public MilestoneCreateResponse createMilestone(@RequestBody MilestoneCreateRequest request) { // Milestone 생성
[참고] `@RequestBody`에 대해서도 학습해보시면 좋을 것 같아요!

2023-05-27 14:33 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/auth/S3Properties.java
> +    }
산토리가 알려주신 자료들이 많이 도움이 되었습니다! 감사합니다 😭

2023-05-27 14:42 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/config/AmazonS3Config.java
> +@EnableConfigurationProperties(value = {S3Properties.class})
참고해보고 수정해보겠습니다!

2023-05-27 14:59 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
> +        return ResponseEntity.ok().body(labelList);
잘 모르겠습니다..
컨트롤러에서 어떤 값을 반환해줘야할지 모르겠어서 전 기수분들의 컨트롤러를 찾아보니 ResponseEntity를 많이 사용하길래 찾아보니 클라이언트에서 변경에 용이하다고하여 사용했습니다.

2023-05-27 15:11 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueResponse.java
> +    private List<Label> labels;
앗... 확인했습니다! 실수한 것 같습니다

2023-05-27 15:19 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueResponse.java
> +    private List<Label> labels;
`
private List<LabelResponse> labels;
    private Long milestoneId;
    private boolean isOpened;

    public static IssueResponse from(Issue issue) {
        return new IssueResponse(issue.getId(), issue.getTitle(),issue.getCreatedAt(), LabelResponse.from(issue.getLabels()),issue.getMilestoneId().getId(),issue.getIsOpened());
    }
`

2023-05-27 15:19 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/issuedto/IssueResponse.java
> +    private List<Label> labels;
`public static IssueResponse from(Issue issue) {
        return new IssueResponse(issue.getId(), issue.getTitle(),issue.getCreatedAt(), LabelResponse.from(issue.getLabels()),issue.getMilestoneId().getId(),issue.getIsOpened());
    }`

2023-05-27 15:21 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
> +    @Query("SELECT * from Issue where status = :isOpened")
열린 상태의 id만 조회하려고 따로 쿼리를 작성했습니다

2023-05-27 15:22 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/label/Label.java
> +    @NotBlank
NotNull과 공백을 방지하려고 사용했습니다

2023-05-27 15:25 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    private AggregateReference<Milestone, @NotNull Long> milestoneId;
아직 어그리거트 루트가 뭔지 정확히는 모르겠지만.. milestone이 issue의 어그리거트라고 생각하고 짰습니다

2023-05-27 15:27 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    private AggregateReference<Milestone, @NotNull Long> milestoneId;
N:m의 관계인 label은 @MappedCollection을 사용하였고, 1:n인 mileston은 AggregateReference를 사용하였는데, 이게 Spring Data JDBC에서 one to many, many to many를 표현할 수 있다해서 사용했습니다

2023-05-27 15:37 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        Issue issue = issueRepository.findById(issueId).orElseThrow();
`        Issue issue = issueRepository.findById(issueId).orElseThrow(IllegalArgumentException::new);
`
로 수정해줬습니다

2023-05-27 15:39 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        Issue issue = issueRepository.findById(issueId).orElseThrow();
시간이 남는다면 exception handler를 구현해보겠습니다...시간이....남는다면......

2023-05-27 15:42 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        return responseList;
아 기본이 열린이슈만 가져오기인데 닫힌이슈도 잘 와지는지 확인하려고 만들었습니다. 해당 기능은 필터라고 생각하는데 저희는 필터를 구현하지 않아서 이 메소드를 어떻게 써야할지 잘 모르겠습니다

2023-05-27 15:48 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        return responseList;
`    public List<Issue> getIssues(@RequestParam(defaultValue = "true") Boolean isOpened) {
`
Controller 에서 이렇게 받아서 기본값이 true 로 되게하고
```
public List<Issue> findByOpenIssue(Boolean isOpened) {
        List<Issue> openIssues = issueRepository.findByIsOpened(isOpened);
        List<Issue> responseList = new ArrayList<>();   // 모든 열린 이슈들, 각각의 라벨
        for (Issue openIssue : openIssues) {
            responseList.add(findById(openIssue.getId()));
        }
        return responseList;
    }
```
Service에서 로직을 이렇게 변경했습니다

2023-05-27 15:53 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
> +        Label targetLabel = labelRepository.findById(id).orElseThrow(() -> new NotFoundException(HttpStatus.NOT_FOUND + "정보를 찾을 수 없습니다"));
아마 500에러가 날 것 같습니다.. 예외처리하는 클래스를 하나 생성해보겠습니다(Controller advice?)

2023-05-27 16:08 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        return responseList;
좋은 것 같네요!!

2023-05-27 16:12 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/IssueService.java
> +        Issue issue = issueRepository.findById(issueId).orElseThrow();
넵 좋습니다 ㅎㅎ 다 챙기지 못하셔도 좋아요
이후 프로젝트나 시간이 남을 때 예외처리도 꼼꼼히 챙겨두시면 좋을 것 같네요! 개인적으로는 예외처리가 잘될수록 API의 완성도가 올라간다고 생각합니다 ㅎㅎ

2023-05-27 16:20 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/repository/IssueRepository.java
> +    @Query("SELECT * from Issue where status = :isOpened")
아 그렇군요! 근데 findByStatus를 이용하고status값에 해당 이슈가 open인지 close인지 여부를 받으면 기능은 똑같고 쿼리 작성할 필요가 없지 않나라는 생각이 들어서 코멘트 남겼습니다!

2023-05-27 16:33 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    private AggregateReference<Milestone, @NotNull Long> milestoneId;
https://velog.io/@given53/Spring-Spring-Data-JDBC 
요 글이 애그리거트에 대해 가볍게 읽어볼만한 글일 것 같은데요. 
한번 읽어보시고 애그리거트가 무엇인지, 애그리거트 루트는 무슨 역할인지 조금 감을 잡아보시면 좋을 것 같아요!

이해가 조금 되시면 아래 글이 조금 더 심화된 내용을 다루고 있는 것 같네요!
https://velog.io/@gentledot/ddd-aggregate

2023-05-27 16:33 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/label/Label.java
> +    @NotBlank
혹시 정말 방지가 되는지 검증해보셨나요?

2023-05-27 17:25 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
> +        targetLabel.editLabel(request.getTitle(), request.getDescription(), request.getBackgroundColor(), request.getFontColor());
....어.......?

2023-05-27 17:26 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
> +        targetLabel.editLabel(request.getTitle(), request.getDescription(), request.getBackgroundColor(), request.getFontColor());
```
public LabelResponse edit(Long id, LabelRequest request) {
        Label targetLabel = labelRepository.findById(id).orElseThrow(() -> new NotFoundException(HttpStatus.NOT_FOUND + "정보를 찾을 수 없습니다"));
        targetLabel.editLabel(request.getTitle(), request.getDescription(), request.getBackgroundColor(), request.getFontColor());
        labelRepository.update(targetLabel.getId(), targetLabel.getTitle(), targetLabel.getDescription(), targetLabel.getBackgroundColor(), targetLabel.getFontColor());
        return LabelResponse.from(targetLabel);
    }
```

2023-05-27 17:26 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
> +        targetLabel.editLabel(request.getTitle(), request.getDescription(), request.getBackgroundColor(), request.getFontColor());
시도해봣는데 객체로 매핑이 안되서 결국 하나하나 파람값을 넣어줬습니다....
```
 @Modifying
    @Query("UPDATE label SET title = :title, description = :description, background_color =:backgroundColor, font_color =:fontColor where label_id = :id")
    void update(Long id, String title, String description, String backgroundColor, String fontColor);
```

2023-05-27 17:35 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    private List<Label> labels = new ArrayList<>();
```
public void addLabel(Label label){
        labels.add(label);
        issueLabels.add(new IssueRefLabel(label.getId(),id));
    }

```
issue가 label들을 가지고 있고 Label은 issue를 가지고 있어서 n:m관계로 표현했습ㄴ다
```
{
        "id": 1,
        "title": "이슈 1번 제목",
        "contents": "이슈 1번 내용",
        "isOpened": true,
        "createdAt": "2023-04-25T00:00:00",
        "milestoneId": null,
        "labels": [
            {
                "id": 1,
                "title": "수정되라고요",
                "description": "레이블 1번 설명",
                "backgroundColor": "#00FF00",
                "fontColor": "LIGHT",
                "issueLabels": [
                    {
                        "labelId": 1,
                        "issueId": 1
                    }
                ]
            },
            {
                "id": 2,
                "title": "레이블 2번 제목",
                "description": "레이블 2번 설명",
                "backgroundColor": "##FFFF00",
                "fontColor": "DARK",
                "issueLabels": [
                    {
                        "labelId": 2,
                        "issueId": 1
                    },
                    {
                        "labelId": 2,
                        "issueId": 2
                    }
                ]
            }
        ],
        "issueLabels": [
            {
                "labelId": 1,
                "issueId": 1
            },
            {
                "labelId": 2,
                "issueId": 1
            },
            {
                "labelId": 1,
                "issueId": 1
            },
            {
                "labelId": 2,
                "issueId": 1
            }
        ]
    },
```
JSON에선 이렇게 표현됩니다

2023-05-28 01:56 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/service/LabelService.java
> +        targetLabel.editLabel(request.getTitle(), request.getDescription(), request.getBackgroundColor(), request.getFontColor());
save를 하면 아마 자체적으로 UPDATE문으로 나갈텐데요! 한번 해보시기 바래요 ㅎㅎ

2023-05-28 01:58 UTC, seyoung755 commented on BE/src/main/java/team05/codesquad/issuetracker/domain/issue/Issue.java
> +    private List<Label> labels = new ArrayList<>();
아아 넵 그렇군요~ 좋습니다!
Issue 내의 labels가 그대로 클라이언트가 노출되지 않도록 dto 사용만 잘 신경써주시면 될것같아요!

2023-05-28 04:30 UTC, KOKEONHO commented on BE/src/main/java/team05/codesquad/issuetracker/controller/MilestoneController.java
> +    }
넵 알겠습니다 ! 컨벤션 수정토록 하겠습니다.

2023-05-28 10:01 UTC, seyoung755 commented
우선 PR은 머지하도록 하겠습니다 :) 고생하셨습니다!

2023-05-28 10:01 UTC, merged

2023-05-28 11:39 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
> +        Iterable<Label> labelList = labelService.findAll();
Spring Data JDBC에서 CrudRepository를 사용하는데, findAll() 메소드 자체가 Iterable을 반환하여서 사용할 수 있는 방법이 
1. (List<>)로 바인딩한다
2. StreamSupport를 사용한다
산토리가 알려주신방법으로 사용할 수 있었군요.....수정했습니다

2023-05-28 11:42 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/LabelController.java
> +    @PatchMapping("/{id}")
put -> 전체, patch -> 일부교체. 근데 전체를 받고있는데 일부를 교체한다고 볼 수 있나? 라고 생각해서 patch를 사용했는데 어차피 id는 변경이 안되는 것이니 put으로 변경했습니다
```
@PutMapping("/{id}") 
    public ResponseEntity<LabelResponse> editLabel(@PathVariable Long id, @RequestBody LabelRequest request) {
        LabelResponse response = labelService.edit(id, request);
        return ResponseEntity.ok().body(response);
    }
```

2023-05-28 15:59 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/MilestoneController.java
> +    @ResponseStatus(HttpStatus.OK)
몰랐습니다. 남들이하길래 따라했습니다.

2023-05-28 16:00 UTC, ninaaano commented on BE/src/main/java/team05/codesquad/issuetracker/controller/IssueController.java
> +        return issueService.findByOpenIssue();
수정하겠습니다!