[team-03] FE 3주차 PR
codesquad-members-2023/issue-tracker pull request #52
Opened 2023-05-26 02:54 UTC by sjuhan123

안녕하세요 빰빰!

이번 주도 잘 부탁드립니다.

감사합니다😄 

# 📍 구현 진행 된 내용

https://github.com/codesquad-members-2023/issue-tracker/assets/81420856/e5112940-67c8-4a26-879d-4c3429618a5a

### 시저
- 이슈 작성 페이지
- 이슈 상세 페이지(진행 중)

### 덴
- 메인페이지 Issue Table 세부 기능
	- 필터
	- 체크박스(구현 예정)
	- 페이지네이션(구현 예정)

4주차는 페어로 로그인 페이지를 집중적으로 구현할 예정입니다.

# 📍  고민 

- 메인페이지(이슈 리스트)와 이슈 작성 페이지에서 전체 라벨 목록, 전체 유저 목록, 라벨 목록을
페칭하여 사용하는데, 매번 페이지를 이동할때마다 페칭을 새로 받다보니 전역 상태로 빼지 않고
페이지 별로 상태관리를 하는데 이게 맞는 방법인지 궁금합니다.

- 또 이슈 작성 페이지에서 인터랙션에 의해 다시 페치되는 일이 없는데,
이런 경우에는 react router에 loader을 사용하는게 맞는지 단순히 useEffect를 사용하는게 맞는지 궁금합니다. (페칭을 해올 수 있는 여러 선택지중 어떤걸 선택해야되는지? 찾아볼만한 키워드들이 있는지 궁금합니다.)

- 오류 처리 및 예외 처리: 비동기 요청 시 발생하는 오류에 대한 적절한 처리를 위해 오류 처리 및 예외 처리 메커니즘을 구현할 예정입니다. 다만 구체적으로 어떤 식으로 구현을 해야 되는지 감이 오지 않습니다. 혹시 추천해주실만한 키워드가 있으신지 궁금합니다.
  - 고민 키워드: 오류 처리 및 예외 처리, 로깅 및 모니터링, 사용자 경험 UI, 재시도 및 복구 메커니즘

2023-05-27 10:05 UTC, Jerome-Yoo commented
안녕하세요! 한 주 고생많으셨습니다.
고민부터 좀 다뤄볼까요?

2023-05-27 10:05 UTC, Jerome-Yoo commented
> 메인페이지(이슈 리스트)와 이슈 작성 페이지에서 전체 라벨 목록, 전체 유저 목록, 라벨 목록을 페칭하여 사용하는데, 매번 페이지를 이동할때마다 페칭을 새로 받다보니
- 그쵸 페이지마다 뭔가 렌더링할 때 데이터를 불러야하면 그럴 수밖에 없지요.

> 전역 상태로 빼지 않고페이지 별로 상태관리를 하는데 이게 맞는 방법인지 궁금합니다.
- 충돌되는 지점은 데이터를 딱 한번만 받아서 렌더링 시점에서 더 데이터를 부르지 않겠다는 마인드 vs 페이지마다 계속 부르자. 인거죠?
- 전자 후자 뭐가 맞고 틀리다 이런 이야기를 하기는 좀 어렵긴 한데요. 
  - 페이지마다 데이터를 새로 받는다는 아이디어는 일반적이기도 하고, 받아와야하는 데이터가 더 없어도 된다면, Route를 페이지 컴포넌트나 그보다 작은 컴포넌트 내부에서 분기쳐지도록 다루는 것도 맞는 방식이긴 해요.
  - 일단 이야기 하고 싶은 건 페이지별로 상태관리 해도 된다. 이구요. 원소스멀티유즈의 관점에서는 좀 꺼려지는 선택인지라, 같이 고민되었으면 하는 주제는 
  - 전역레벨에서 데이터를 관리해서 애플리케이션 복잡성을 올려놓으면 누구에게 이득이고 누구에게 손해일까.
    - 전역레벨에서 데이터를 다루면 애플리케이션의 복잡성이 올라갈까? 
  - 어떤측면에서 마이너스를 감당해야하는 결정인가. 이런 것도 고민해봤으면 좋겠어요.

---
 
- 다만 시야를 하나 열어드렸으면 하는 부분은, "서버로부터 받아온 데이터가 stale하다는 것은 FE입장에서 어떻게 판별할 수 있을까" 예요.
  - 불필요한 캐싱이나 최적화가 애플리케이션을 망친다는 것은 무슨 말일까. 어떻게 받아들여야할까.
  - 우리가 만든 앱을 다수의 사용자가 사용한다면, 변화하는 데이터의 실시간성은 어떻게 보장할 수 있을까.
  - (나중에 공부했으면 싶은) 서버상태라는 말이 몇년전부터 엄청 유행하고 있거든요. 개인적으로는 너무 FE측면에서의 워딩이고, 상태라는 단어를 아무데나 가져다 붙인 것이기도 하고 CS적으로도 맞는 말인가에 대한 의문도 있는데요. 어쨌든 그래서 서버상태와 서버상태가 아닌 것을 나눠서 칭하고 있는 이유는 무엇때문일까.

2023-05-27 10:10 UTC, Jerome-Yoo commented
> 또 이슈 작성 페이지에서 인터랙션에 의해 다시 페치되는 일이 없는데,
> 이런 경우에는 react router에 loader을 사용하는게 맞는지 단순히 useEffect를 사용하는게 맞는지 궁금합니다. (페칭을 해올 수 있는 여러 선택지중 어떤걸 선택해야되는지? 찾아볼만한 키워드들이 있는지 궁금합니다.)
- 저는 사실 리액트라우터의 로더를 써본적이 없어요. 리액트라우터로더가 비교적 최신 스펙이기도 해서인데요, 제가 다뤘던 애플리케이션은 버전 업데이트로부터의 사이드이펙트를 감당할 여유가 없기도 했어요.
- 뭘로 하든 여러분의 자유이긴 한데, 이번 프로젝트가 여러도구를 써보자? 는 주제가 아닌 것 같아서 개인적으로는 useEffect 이외의 선택지에는 deny를 드려보고 싶긴해요. useEffect를 잘못써서 생기는 애플리케이션이 깜빡거려요 하는 문제정도는 다뤄봤으면 좋겠다는 생각이 듭니다.

2023-05-27 10:23 UTC, Jerome-Yoo commented
> 오류 처리 및 예외 처리: 비동기 요청 시 발생하는 오류에 대한 적절한 처리를 위해 오류 처리 및 예외 처리 메커니즘을 구현할 예정입니다. 다만 구체적으로 어떤 식으로 구현을 해야 되는지 감이 오지 않습니다. 혹시 추천해주실만한 키워드가 있으신지 궁금합니다.
-  스읍.. 요 내용으로도 거진 한달은 풍부하게 학습할 수 있는 내용인지라.. 뭘 추천해야하나 고민이군요.. 
- 일단 충분히 런타임 에러를 방어할 수 있는 코드를 짜고 계신지 궁금하구요. 백엔드 에러를 기초적인 수준에서 핸들링 하고 있는지도 좀 궁금합니다. 유저에게는 어떤 UI/UX를 전달하고 계신가요?
- 뭔가 도입할 거리를 찾고 있다면, 일단 에러바운더리부터 학습해보고 도입 해보는 건 어떨까요?

2023-05-28 11:41 UTC, Jerome-Yoo requested changes
고생하셨습니다~ 답변을 반드시 들어야 하는 부분이 있어서 requested changes를 눌렀는데요, [질문] 부분의 답변을 듣고 approve를 찍겠습니다. 지난주부터 여쭤보고 있는 내용도 있어서요🥲 

리뷰를 확인해보시고 궁금한 점이 있으면 코멘트를 작성해주세요!
리뷰가 너무 늦어지면 안되는 지라 제가 미처 체크하지 못한 부분은 연휴중으로 다뤄보도록 해보겠습니다.

고생하셨어요~

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/CommentList/CommentList.jsx
> +import CommentTextArea from '../CommentTextArea/CommentTextArea';
[질문]
[이전 PR](https://github.com/codesquad-members-2023/issue-tracker/pull/41#pullrequestreview-1435423573)에서도 코멘트를 드렸는데요, 답변을 받지 못해서 다시 드려봅니다.
동일한 이름으로 import 한 것까지 따지면 사실상 3번씩 쓰였네요. 저 개인적으로는 이렇게 쓰면 안된다고 생각하는데, 여러분 판단을 듣지 못해서 제안이나 적극 라벨을 달지 않고 질문 라벨로 달아봅니다. 어떻게 판단하고 계신가요?

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/CommentList/CommentList.jsx
> +  const [value, setValue] = useState('');
[적극]
상태로서 다루는 변수명이 너무 일반적입니다. 꼭 고쳐주시기를 기대하고 있겠습니다.

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/CommentList/CommentList.jsx
> +  const [value, setValue] = useState('');
코드를 가만보니 이 컴포넌트가 하는 역할이 실제 코멘트를 업데이트까지는 하지 못하고 있는 상황이군요.
TODO 등의 주석을 꼭 붙여주시기를 부탁드려봅니다

- 학습하는 과정이라 이런 케이스가 밀려오는 것은 어쩔수는 없다고 생각합니다.
만약 리뷰로는 올리고 싶지 않았는데 원치않게 깃에서 다뤄지게된 파일이라면 [git rm --cached]
(https://mygumi.tistory.com/103)로 지울 수 있어요.

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/hooks/useInputFocus.jsx
> +    };
[적극]
이 코드에서는 `inputBoxRef`와 `inputRef`가 각각 `current`로 접근했을 때 `null`일 가능성이 있는 코드인데요, 각각이 `null`일 때는 작동을 하지 않을 수 있도록 핸들링을 해주셔야 할 것 같습니다.
<img width="534" alt="image" src="https://github.com/codesquad-members-2023/issue-tracker/assets/88368753/2cb7625f-a703-43f6-9329-bd40ee533535">
<img width="514" alt="image" src="https://github.com/codesquad-members-2023/issue-tracker/assets/88368753/cc38bc37-13dc-47a6-a3a7-25ffbc99f104">

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +  const DropDownRef = useRef();
LGTM 👍

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
>      };
LGTM 👍

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +    document.addEventListener('click', handleClickOutside, true);
오호 캡쳐링으로 다루고 계시는군요? 변경된 이유가 있을까요?

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +      </DropDownButton>
[질문]
[앞선 리뷰](https://github.com/codesquad-members-2023/issue-tracker/pull/41#discussion_r1199738121)에서 답변을 구했는데, 듣지 못한 상황에서 같은 코드가 올라온 것 같아요. 다시 여쭤봅니다~

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/IssueItem/IssueItem.jsx
> +  state,
[적극]
윽 state라는 이름을 prop으로 내려받는 것이 이상합니다.
무슨 상태를 내려받는거지? 하는 생각이 드는군요.

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/IssueTable.jsx
> +  }
아 이부분은 이렇게 변수로 빼는 처리를 하셨군요. 지난번의 리뷰지점이어서 이렇게 변경된 것으로 보여져요.
이 부분은 code suggestion을 드려보겠습니다.
```suggestion
const issueItems = issues && issues.length !== 0 && (
    issues.map((issue) => <IssueItem key={issue.number} {...issue} />)
  ) 
```

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/IssueTable.jsx
> +      <IssueItemList>{content}</IssueItemList>
이어지는 suggestion입니다.
```suggestion
    {issueItems ? (<IssueItemList>{issueItems}</IssueItemList>) : (<NoticeBox>검색과 일치하는 결과가 없습니다.</NoticeBox>)}
```
`IssueItemList`의 스타일링은 고려하지 않고 suggestion 드린 것이라 스타일링이 필요하면 추가될 수 있겠습니다!

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/IssueTable.jsx
> +      && option !== OPENED,
아래의 맥락을 filterOptions에 한번에 밀어넣고 있어서 쓰는 상황에서 적용되었는지를 판단하기 위해 복잡한 논리식이 쓰인 상황이라 생각해요
```
filterOptions: {
    issueState: OPENED,
    writtenByMe: false,
    assignedToMe: false,
    commentedByMe: false,
    assignee: null,
    labels: [],
    milestone: null,
    author: null,
    // TODO(덴): pagination 기능 구현 필요 & 백엔드와 API 협의 필요
    // page: 1,
  },
```

option이 null 이면서, false이면서, 어떤 건 또 array이기 때문에, 길이값으로 판별해야하고.. 이런 부분이 이전 맥락을 다 알아야해서 생기는 고통스러운 지점이라 생각해요.

이제와서 이 부분을 분리하는게 부담스럽다, 라고 생각할 수도 있을 것 같은데요, IssueTable 컴포넌트가 해당 변수를 사용하는 입장에서 각 값이 어떤지 맥락을 알아야 하는 이유는 없다고 생각해요. 저런 부분을 어딘가에 잘 숨겨볼 수 있을 것 같아요.
filterOptions를 직접다루는 곳에서 검사 해볼 수 있을 것 같기도 하구요, 커스텀훅이나 유틸함수로 위임할 수도 있다고 생각합니다.

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/pages/AddIssue.jsx
> +          />
[제안]
name으로 업데이트 되어야 하는 지점을 change시점마다 판별하는 것으로 보이는군요.
```
 const onChange = ({ target }) => {
    setForm({ ...form, [target.name]: target.value });
  };
```

코드 레벨에서 봤을 때는 굳이 두 상태가 묶여있어야 하는 이유(상호 의존성이 있는 지점)를 찾지 못했는데, 상태를 분리한다면 좀 더 직관적으로 다룰 수 있지 않을까요?

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/IssueTable/TableToolBar/IssueStatusButtons/IssueStatusButtons.jsx
> +        )
이렇게 바꾸면 스트링으로 다룬다는 것을 명시적으로 리터럴로 줄 수 있습니다.
`열린이슈 ${openedIssuesCount}`

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/common/Button/Button.jsx
>  }) => {
[제안]
전반적으로 버튼의 기본값이 선언되지 않아서 모든 버튼에서 prop을 내려줘야 하는 상황인 것 같아요.
예를들면, type= "ghostButton", size= "M", color= "neutral...", hoverColor = "neutral..." 이런식으로 선언부에서 기본값 선언을 시도해보시는 것은 어떨까요.

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/components/common/Button/Button.jsx
> +  };
`<Button type="containerButton | outlineButton | ..."> </Button>` 이런식으로 버튼의 맥락이 여러번 불리는 지라 서로 크게 다르다면, 아예 타입별로 쓰이는 버튼을 별도로 만드는 것도 방법이에요.
`<ContainerButton> <OutlineButton> <GhostButton>`

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/constants.js
> +};
같은 상수여도 위의 것들과 다르게 형태가 다르다면, src/constants 말고 다른형태로 관리하는게 좋을 수도 있습니다.
TableFilterButtons에서만 쓰이고 있는 것으로 보여지는데, 그 하위에서 constants.js를 만들고 관리하거나 아예 그 컴포넌트에서 관리되어도 될 것 같아요.

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/context/MainPage/MainPageContext.jsx
> +  );
오 두 Provider를 나누셨네요. 최적화 측면에서의 고려가 된 선택인거죠?

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/pages/IssueList.jsx
> +      dispatch(setMainPageState(mainPageData));
[질문] 혹시 여기서 filteroptions 이외의 나머지 맥락이 한번에 업데이트 되나요?

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/context/MainPage/MainPageContext.jsx
> +const mainPageReducer = (state, action) => {
이 리듀서가 mainPage라는 맥락을 담게 된 것은 이런 결정이 있었기 때문이라고 생각해요.
1. 메인페이지에서 쓰이는 모든 맥락을 담았다.
2. 그러다 보니 filterOptions도, 그외의 issues나 users 등도 한번에 쓸 수 밖에 없다.
  - 뭐가 쓰이는지 체크하려면 initialValue를 반드시 봐야한다.

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/context/MainPage/MainPageContext.jsx
> +const mainPageReducer = (state, action) => {
지금 수정되기에는 너무 먼 길을 오긴했지만
`action.payload` 에 true false가 계속 쓰이는 형태라면 굳이 key:Value의 형태가 아니어도 될 것 같다는 생각을 해요.
"filters: [key1, key2, key3]" 이런 구조도 괜찮을 수 있겠다는 생각이 드는군요.

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/pages/AddIssue.jsx
> +  };
[적극]
이 로직들은 컴포넌트를 쓸 때 모든 맥락을 몰라도 Addissue를 쓸 수 있을 거예요. custom 훅에 밀어넣어놓고 해당 훅으로부터 AddIssue에게 드러나야하는 부분만 드러내는 형태로 해서 개선해보면 어떨까요.

[참고]
fetch하는 부분은 공통 훅으로 만들어볼 수도 있습니다.
https://plainenglish.io/blog/custom-hook-in-react-js-for-calling-api-useapi
1주일안에 만들어보라는건 아니구요, 학습하실때 해보셔요 ㅎㅎ

2023-05-28 11:41 UTC, Jerome-Yoo commented on fe/src/context/MainPage/MainPageActions.js
> +};
중복되는 부분은 이런식으로 바꿔볼 수도 있겠군요. 코드레벨에서 작성해서 로직이 약간 깨져있을 수도 있어요. 의사코드 정도라고 이해해주시면 좋을 것 같아요!

```suggestion
const createCommonAction = (key, type) => {
  return {
    [key]: (value) => ({type, payload: value})
  }
}

const filterOptionTypeActionMap = {
  [RESET_FILTER_OPTIONS]: 'reset',
  [SET_ISSUE_STATE_FILTER_OPTION]: 'issueState'
  ...
}

export const filterOptions = Object.entries(filterOptionTypeActionMap).reduce( (accumulatedOptions, [type, key]) => {
  return {...accumulatedOptions, ...createCommonAction(key, type)}
}, {})
```

2023-05-28 11:45 UTC, Jerome-Yoo commented on fe/src/components/CommentList/CommentList.jsx
> +  const [value, setValue] = useState('');
주석 쓰는게 부담이면 회의록 같은거라고 공유되었으면 좋겠어요 🥲

2023-05-28 11:56 UTC, Jerome-Yoo commented on fe/src/pages/AddIssue.jsx
> +  };
논란의 여지가 있을 수는 있지만, 저는 공통으로 쓰이는 부분만이 커스텀훅으로의 전환 대상이다 라고는 생각하지 않아용

2023-05-28 14:55 UTC, sjuhan123 commented on fe/src/components/CommentList/CommentList.jsx
> +import CommentTextArea from '../CommentTextArea/CommentTextArea';
저희가 생각한 해결방안은 index.jsx 사용하기 였지만 하나의 폴더 안에 하나의 파일만 있는데, index.jsx를 사용하는 것이 어색하게 느껴져서, 다른 해결방안이 있을까 고민하다가 결정하지 못하고 넘어갔었습니다. 😢 
하지만 빰빰님 말씀처럼 동일한 이름을 3번씩 사용하는 것은 더 어색하고 필요하지 않다는 것을 느낍니다. 이 부분은 이번 리뷰 이후에 시저와 논의해서 수정하겠습니다.

2023-05-28 15:04 UTC, sjuhan123 commented on fe/src/context/MainPage/MainPageContext.jsx
> +  );
네 맞습니다. 
상태와 디스패치를 두개의 context로 분리하면, 상태가 업데이트 되더라도 디스패치 컨텍스트에는 변화가 없어 해당 컨텍스트를 사용하는 하위 컴포넌트들은 다시 렌더링 되지 않는 등 불필요한 컴포넌트 업데이트(리렌더링)를 방지할 수 있어 최적화에 도움이 될 거라 생각해서 분리하게 됐습니다.

2023-05-28 15:07 UTC, sjuhan123 commented on fe/src/components/IssueTable/IssueItem/IssueItem.jsx
> +  state,
앗 이부분은 얼른 수정하겠습니다😮

2023-05-28 15:24 UTC, sjuhan123 commented on fe/src/pages/IssueList.jsx
> +      dispatch(setMainPageState(mainPageData));
네! 여기서 filterOptions 제외 아래 나머지 맥락들이 한번에 업데이트 됩니다.
```js
issues: [],
counts: {},
allUsers: [],
allLabels: [],
allMilestones: [],
```

2023-05-28 15:30 UTC, sjuhan123 commented on fe/src/components/IssueTable/TableToolBar/IssueStatusButtons/IssueStatusButtons.jsx
> +        )
혹시 뷰에 '열린이슈(숫자)' 이렇게 나타나야 되는데, 아래와 같은 수정 방향이 맞을까요?
```js
열린이슈 `($
   {openedIssuesCount}
)`
```

2023-05-28 15:38 UTC, Jerome-Yoo commented on fe/src/pages/IssueList.jsx
> +      dispatch(setMainPageState(mainPageData));
그렇군요. 분리가 되면 좋겠다는 생각이 들지만, 다음 프로젝트 마감이 1주일 남은 상황에서 수정이 헤비할 것 같다는 생각이 들어요.
전역 상태를 의미단위로 분리하는 방법은 다른 도구들에서도 일반적으로 쓰이는 방식이기도 해요.
이를 비슷하게 ContextAPI에서 따라서 구현할 수도 있는데요 [Provider를 분리하는 요령이 담긴 아티클](https://javascript.plainenglish.io/how-to-combine-context-providers-for-cleaner-react-code-9ed24f20225e)을 학습 목적으로 권해드립니다

2023-05-28 15:39 UTC, Jerome-Yoo approved these changes
앞선 질문 코멘트는 확인을 했습니다. [이쪽 코멘트](https://github.com/codesquad-members-2023/issue-tracker/pull/52#discussion_r1208482936)만 체크 부탁드려요~ 일단 Approve 찍어두겠습니다

2023-05-28 15:53 UTC, sjuhan123 commented on fe/src/components/IssueTable/IssueTable.jsx
> +      && option !== OPENED,
처음 filter option 상태들을 어떻게 관리해야 될지 고민할 때, filter option들을 같은 맥락으로 생각해서, 하나의 객체로 묶어서 관리하는 것이 적합하겠다고 판단했습니다.
다만 기능 구현을 진행하면서, 빰빰이 말씀하신 것 처럼 option 각각의 value 타입이 달라서 생기는 여러  불편함을 느꼈지만, 이를 해결할 해결 방안이 떠오르지 않았는데요.
혹시 빰빰이라면, 이 option 상태들을 각각의 상태로 분리하여 관리하셨을지 궁금합니다.

2023-05-29 04:48 UTC, zlx454545 commented on fe/src/pages/AddIssue.jsx
> +          />
인풋을 여러개 다룰때 이런식으로 하면 핸들러를 여러개 만들필요없어진다고 해서 적용해본 기술이었습니다. 
단순히 값만 입력받고 서버에 전송하기 위해 저장하는 용도라면 이 형태가 좋을 것 같은데

value 들이 다른 로직에 사용되는 경우에 불편함을 느꼈습니다. 수정하도록 하겠습니다!

2023-05-29 05:42 UTC, zlx454545 commented on fe/src/pages/AddIssue.jsx
> +  };
고민하던 부분인데 감사합니다!!

2023-05-29 06:11 UTC, zlx454545 commented on fe/src/components/DropDown/DropDown.jsx
> +      </DropDownButton>
저번 리뷰에 대해서 질문 주신 부분을 사실 잘 이해하지 못했습니다.
혹시 어떤 부분에 대해서 질문 주신 건지 다시 부탁드릴 수 있을까요?

2023-05-29 06:11 UTC, zlx454545 commented on fe/src/components/DropDown/DropDown.jsx
> +    document.addEventListener('click', handleClickOutside, true);
디버깅하다가 남긴 코드였습니다 죄송합니다 😂

2023-05-30 01:19 UTC, Jerome-Yoo commented on fe/src/components/DropDown/DropDown.jsx
> +      </DropDownButton>
> 리액트의 상태 업데이트가 배칭 작업으로 인해 매번 동기적으로 작동하지 않다보니

@zlx454545 아 배칭작업으로 인해 매번 동기적으로 작동하지 않는 상황이 지금 실제로 그런 상황인지를 여쭸었던 거예요!

2023-05-30 01:19 UTC, Jerome-Yoo approved these changes
일단 작업을 하셔야 하는 평일이 된 관계로 Approve로 찍어두겠습니다!

2023-05-30 01:20 UTC, merged

2023-05-30 08:00 UTC, caesar1030 commented on fe/src/components/DropDown/DropDown.jsx
> +      </DropDownButton>
![일반](https://github.com/codesquad-members-2023/issue-tracker/assets/76683390/318005e7-d4b8-4e69-9d76-256c2a4b0e03)
![함수형업데이트](https://github.com/codesquad-members-2023/issue-tracker/assets/76683390/fdf19d05-a2fd-4590-8f97-5d0dbadc59e2)

질문 주신 부분이 이 부분이 맞는지 확신이 들지는 않지만
click 이벤트를 코드 상으로 빠르게 연속 두번 발생시켰을때 

setIsOpen(!isOpen)으로 작성한 경우는 isOpen이 한번 토글되어 기존의 상태가 되지 않는 사소한 버그가 발생하고,

setIsOpen((prev)=>setIsOpen(!prev))로 작성한 경우는 isOpen이 두번 토글되어 원상태로 그대로 유지됩니다.

따라서 이전 상태에 의존하여 상태를 업데이트 할 경우는 함수형 업데이트를 사용하였습니다! 
혹시 제가 오개념을 가지고 있었던걸까요?