[Team-03] BE 4주차 리뷰 PR
codesquad-members-2023/issue-tracker pull request #69
Opened 2023-06-02 02:54 UTC by ghkdgus29

# 구현 사항 
- 이미지 업로드 기능 구현 
- 이슈 상세 조회 기능 
- 리팩토링 및 버그 수정 

### 회고 
이번주는 크게 로직을 만들지 않고, 기존에 있던 기능들을 리팩토링하고, 버그를 수정하는 한 주를 보냈습니다. 

이번 프로젝트동안 열심히 리뷰해주셔서 정말 감사드리고, 짚어주신 내용들 공부하는 시간을 가지도록 하겠습니다!

2023-06-03 03:34 UTC, kses1010 requested changes
즐거운주말에  실례하겠습니다! 프론트 코드와 섞여있습니다. 다시 올려주시겠어요?

2023-06-03 05:48 UTC, ghkdgus29 commented
FE 패키지 제거했습니다 !

2023-06-03 06:31 UTC, kses1010 reviewed
고생하셨습니다! 이번 PR은 대부분 리팩토링에 많이 신경쓰신게 많이 느껴지네요

일요일 오후5시까지 리뷰 질문답변을 받을게요!

고생하셨습니다!!

2023-06-03 06:31 UTC, kses1010 commented on be/build.gradle
> +	implementation 'org.springframework.cloud:spring-cloud-starter-aws:2.2.6.RELEASE'
이건 왜 추가하신건가요?

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/configuration/S3Config.java
> +    }
아하 aws cloud의존성을 추가한 이유가 이미지 업로드 용이었군요

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/configuration/WebConfig.java
> +                .allowedMethods("GET", "POST", "HEAD", "PUT", "DELETE", "OPTIONS", "PATCH");
`*`에서 메소드로 전부 추가하신 이유가 무엇인가요?

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/image/ImageController.java
> +    }
여기서도 Map으로 응답하셨는데 이렇게 설정하신 이유가 무엇인가요? 이렇게 설정하면 실패해도 StatusCode가 200이 뜨지 않나요?

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    private static final Logger log = LoggerFactory.getLogger(S3UploaderService.class);
Java 컨벤션에 맞춰 순서를 지키면 좋을듯 합니다!

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    private String bucket;
여기도 마찬가지로 순서를 지켜주세요!!

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    }
여기서 IOException을 던지지말고 여기서 catch해서 컨트롤러까지 올라오지 않도록하는건 어떻게 생각하세요?

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    }
여기서 리턴값을 Optional로 주기보단 만약 없다면 바로 예외처리하는것도 나쁘지않습니다. 그럼 호출할 당시 Optional로 처리할 필요가 없습니다. 위 코드에서도 만약 null일 때 다른 비즈니스코드로 처리하는게 아니라 예외처리로 하고 있거든요

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/issue/IssueRepositoryImpl.java
> +        }
네 맞습니다. 이럴땐 유효성 검사를 객체 내부에서 처리한다면 서비스층에서 좀더 깔끔하게 작성이 가능합니다.

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/issue/IssueRepositoryImpl.java
> +        if (issueUpdateFormDTO.getMilestoneName() != null && !issueUpdateFormDTO.getMilestoneName().equals("$none") && issueMapper.validMilestone(issueUpdateFormDTO.getMilestoneName()) != 1) {
여기도 마찬가지로 메서드추출하면 좋겠네요 실제 `$none`이란게 코드에선 바로 알기가 어렵거든요

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/issue/IssueRepositoryImpl.java
> +        if (issueCreateFormDTO.hasAssigns()) {
메소드로 추출해서 해당 조건문이 어떤걸 의미하는지 확실히 알수 있겠네요

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/issue/dto/AllLabelsAndMilestonesAndUsersDTO.java
> +    }
Iterable을 사용한 이유가 무엇인가요? List를 받고 나서 내부에서 처리해도 되지 않을까요?

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/issue/dto/IssueCreateFormDTO.java
> +    }
객체 내부에서 처리하였군요!

2023-06-03 06:31 UTC, kses1010 commented on be/src/main/java/com/example/be/issue/dto/IssueDetailedDTO.java
> +    public List<Comment> comments;
여기 한줄 띄운건 어떤 의미인가요?

2023-06-03 06:31 UTC, kses1010 commented on be/src/test/java/com/example/be/issue/IssueRepositoryTest.java
> +//        }
코드에 주석처리한 건 좋지 않습니다. 특히 테스트코드에서 주석으로 처리한다면 나중에 테스트한다는 뜻인데 시간지나면 실제 이 테스트와 맞지않게 비즈니스 코드가 작성할 가능성이 높아 이 코드가 쓸모없어지는 경우가 많습니다.

만약 테스트가 맞지 않는다면 삭제하고 테스트를 다시 작성하는걸 추천합니다. 그래도 필요하다면 이 테스트가 존재했던 git으로 돌아가 해당 코드를 가져오면 됩니다.

이런 주석처리는 나중에 유지보수하는데 큰 하자가 발생할 수 있으니 꼭 주의하시길 바랍니다!

2023-06-04 02:27 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/configuration/S3Config.java
> +    }
네 맞습니다!

2023-06-04 02:27 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/configuration/WebConfig.java
> +                .allowedMethods("GET", "POST", "HEAD", "PUT", "DELETE", "OPTIONS", "PATCH");
모든 메서드를 열어주기 위해 와일드카드를 사용하였는데, 명시하는게 더 좋겠군요!

2023-06-04 02:28 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/image/ImageController.java
> +    }
그렇겠네요.

차라리 실패한 경우, 에러를 던져주고 예외를 잡아 응답하는게 더 좋겠네요!

2023-06-04 02:29 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/image/ImageController.java
> +    }
Map으로 응답한 건 급하게 하다보니 Map 으로 만든건데 클래스를 만들어서 좀 더 rest 한 응답을 전달하는 게 좋은 방법 같네요

2023-06-04 02:30 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    private static final Logger log = LoggerFactory.getLogger(S3UploaderService.class);
해당 내용 반영해서 수정하겠습니다!

2023-06-04 02:34 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    }
만약 catch 한다면, 제대로 처리되지 않았음을 표현하는 api 응답을 만들어 컨트롤러 단에 전달해야 할까요?

2023-06-04 02:37 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    }
그렇다면 예외를 컨트롤러로 던져야 할까요? 
아니면 잘못됐음을 알리는 api 응답을 만들어 컨트롤러로 전달해야 할까요?

2023-06-04 02:38 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/issue/IssueRepositoryImpl.java
> +        if (issueCreateFormDTO.hasAssigns()) {
말씀해주신대로 DTO 내부로 조건문을 집어넣으니까 훨씬 보기 좋은 것 같습니다!!
좋은 조언 감사합니다!

2023-06-04 02:39 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/issue/dto/AllLabelsAndMilestonesAndUsersDTO.java
> +    }
Spring Data JDBC 에서 제공하는 CRUD Repository 는 특별히 명시해주지 않으면 `Iterable` 로 결과물을 반환하는데, 
이를 서비스 로직에서 List로 변환하는 것 보단, DTO 내부에서 변환해주는 게 좋지 않을까 하여 이런식으로 변환하였습니다.

2023-06-04 02:39 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/issue/dto/IssueCreateFormDTO.java
> +    }
네 맞습니다!

2023-06-04 02:40 UTC, ghkdgus29 commented on be/src/test/java/com/example/be/issue/IssueRepositoryTest.java
> +//        }
좋은 조언 감사합니다!

테스트 코드 관련해서 특히 많은 조언 해주셔서 큰 도움이 됐습니다!

2023-06-04 04:24 UTC, kses1010 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    }
그러셔도 되고  IOException경우엔 개발자가 코드단에서 처리하기가 힘들경우엔 500에러로 잡아 처리하시면 됩니다.

2023-06-04 04:25 UTC, kses1010 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    }
예외를 컨트롤러로 던지기보단 Exception을 호출해서 ControllerAdivce에서 처리하든 여기서 처리하면 되겠죠? 아니면 여기서 처리해도됩니다

2023-06-04 04:26 UTC, kses1010 commented on be/src/main/java/com/example/be/issue/dto/AllLabelsAndMilestonesAndUsersDTO.java
> +    }
객체 컬렉션 타입을 지정할 수 있을것 같은데 안되나요? CRUD Repository에서 원하는 데이터를 쿼리할 때 원하는 객체 컬렉션타입으로 지정할 수 없나요?

2023-06-04 05:03 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    }
답변 감사합니다!

2023-06-04 05:04 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/image/S3UploaderService.java
> +    }
그렇다면 ControllerAdvice에서는 api 요청을 실패했을때 응답해줄 실패 클래스를 반환해줘야겠네요!

2023-06-04 05:09 UTC, ghkdgus29 commented on be/src/main/java/com/example/be/issue/dto/AllLabelsAndMilestonesAndUsersDTO.java
> +    }
Spring Data 공식문서를 봤을 땐, 3.0 버전 이상에선 `ListCrudRepository` 추가되어, List 타입을 반환하지만, 
현재 사용하는 버전에선 자동으로 구현된 crud 메서드 사용시,  `List` 를 반환하는 방법은 찾지 못했습니다!

2023-06-04 05:10 UTC, kses1010 commented on be/src/main/java/com/example/be/issue/dto/AllLabelsAndMilestonesAndUsersDTO.java
> +    }
아하 그렇군요 List타입 반환이 안되는거였군요 되게 별로네요 허허헣

2023-06-04 05:33 UTC, dltpwns0 commented on be/src/main/java/com/example/be/configuration/WebConfig.java
> +                .allowedMethods("GET", "POST", "HEAD", "PUT", "DELETE", "OPTIONS", "PATCH");
현재 백엔드 서버와 프론트엔드 서버가 다른 도메인에서 실행중입니다. (비용 문제로, 2개의 계정으로 2개의 인스턴스를 만들었습니다.)
따라서 동일 출처 정책을 완화하기 위해 cors를 사용했습니다.

하지만, PATCH 요청시에 알 수 없는 에러가 발생했고, Http Method를 명시적으로 변경하니 제대로 동작하게 되었습니다.

왜 명시적으로 변경하니까 동작하는지는 잘 모르겠습니다.

2023-06-04 05:40 UTC, dltpwns0 commented on be/src/main/java/com/example/be/issue/IssueRepositoryImpl.java
> +        if (issueUpdateFormDTO.getMilestoneName() != null && !issueUpdateFormDTO.getMilestoneName().equals("$none") && issueMapper.validMilestone(issueUpdateFormDTO.getMilestoneName()) != 1) {
넵! 다음 프로젝트에서는 DTO가 유효성 검사를 하도록 해보겠습니다!

2023-06-04 05:42 UTC, kses1010 commented on be/src/main/java/com/example/be/configuration/WebConfig.java
> +                .allowedMethods("GET", "POST", "HEAD", "PUT", "DELETE", "OPTIONS", "PATCH");
신기하네요 따로 명시를 해야 동작을하는군요

2023-06-04 08:02 UTC, kses1010 approved these changes
프로젝트동안 고생많으셨습니다!!! 앞으로도 즐거운 코딩하시길~!

2023-06-04 08:02 UTC, merged

2023-06-04 08:42 UTC, ghkdgus29 commented
프로젝트 기간동안 꼼꼼히 리뷰해주셔서 감사합니다!!

2023-06-04 11:49 UTC, dltpwns0 commented
그동안의 리뷰 정말 감사했습니다!
써니님의 리뷰를 기반으로 성장해 보겠습니다! ㅎㅎ